In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../Delivery truck trips data/delivery_trucks_cleaned.csv", low_memory=False)

In [3]:
df

,BookingID,Market/Regular,BookingID_Date,vehicle_no,Origin_Location,Org_lat_lon,Des_lat_lon,Data_Ping_time,Planned_ETA,actual_eta,Curr_lat,Curr_lon,ontime,delay,DestinationLocation_Code,trip_start_date,trip_end_date,TRANSPORTATION_DISTANCE_IN_KM,vehicleType,Minimum_kms_to_be_covered_in_a_day,Driver_Name,customerID,supplierID
0,VCV00014271/082021,Regular,8/27/2020,TN30BC5917,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","12.8390,79.9540","12.8390,79.9540",40:28.0,22:22.8,8/28/2020 12:46,12.836757,79.954428,G,unknown,CHEMATDMROPA7,8/27/2020 16:21,unknown,103.0,unknown,250.0,RAMESH,DMREXCHEUX,VJLEXSHE09
1,VCV00014382/082021,Regular,8/27/2020,TN22AR2748,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","11.8710,79.7390","11.8710,79.7390",05:09.0,59:25.0,8/28/2020 16:03,13.073956,80.225780,G,unknown,CHEPONLUTCCA4,8/27/2020 17:57,unknown,300.0,unknown,250.0,GIRI,LUTGCCHE06,GSTEXLAK1Q
2,VCV00014743/082021,Regular,8/28/2020,TN28AQ0781,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","12.8390,79.9540","12.8390,79.9540",40:31.0,48:24.5,8/28/2020 12:50,12.836686,79.950560,G,unknown,CHEMATDMROPA7,8/28/2020 0:47,unknown,61.0,unknown,250.0,RAVI,DMREXCHEUX,ARVEXNAM09
3,VCV00014744/082021,Regular,8/28/2020,TN68F1722,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","11.8720,79.6320","11.8720,79.6320",40:29.0,23:19.2,8/28/2020 14:22,12.429501,79.831556,G,unknown,CHENETLUTCCA1,8/28/2020 1:13,unknown,240.0,unknown,250.0,TAMIL,LUTGCCHE06,SRTEXKOR96
4,VCV00014749/082021,Regular,8/28/2020,TN88A4980,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","12.8390,79.9540","12.8390,79.9540",40:28.0,14:22.6,8/28/2020 13:25,13.017365,79.962313,G,unknown,CHEMATDMROPA7,8/28/2020 2:13,unknown,70.0,unknown,250.0,GANESH,DMREXCHEUX,ESWEXNAM02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,AEIBK1910732,Regular,12/30/2019,OD14L7676,"Garudagaon, Cuttack, Odisha","16.560192249175344,80.792293091599547","20.40294,86.489546",25:11.0,55:49.0,1/8/2020 2:36,20.579810,86.030420,unknown,R,LE005683,12/30/2019 18:23,1/11/2020 20:49,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40,999
3447,AEIBK2011419,Regular,1/7/2020,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh","16.5094,80.82117","16.823398,80.074446",05:50.0,09:40.0,1/8/2020 3:09,16.531475,80.515490,unknown,R,LE005847,1/7/2020 14:56,1/10/2020 14:11,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40,60169
3448,AEIBK1910132,Regular,12/26/2019,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand","23.675623,86.096278","23.530626,85.458186",20:13.0,21:20.0,1/5/2020 2:59,23.640325,86.102707,unknown,R,LEC06490,12/26/2019 19:56,1/11/2020 17:16,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40,57828
3449,AEIBK1909663,Regular,12/21/2019,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand","23.67348,86.129379","23.530626,85.458186",50:13.0,00:49.0,1/2/2020 3:39,23.586198,86.328034,unknown,R,LE005263,12/21/2019 18:48,1/11/2020 17:16,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40,57828
3450,AEIBK1906955,Regular,11/30/2019,GJ15UU7437,"Changodar, Ahmedabad, Gujarat","16.560192249175344,80.792293091599547","23.042185,72.697893",50:15.0,34:27.0,12/11/2019 3:36,22.190830,73.078550,unknown,R,LE005101,11/30/2019 15:10,1/2/2020 14:24,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40,66198

In [4]:
df.dtypes

BookingID                              object
Market/Regular                         object
BookingID_Date                         object
vehicle_no                             object
Origin_Location                        object
Org_lat_lon                            object
Des_lat_lon                            object
Data_Ping_time                         object
Planned_ETA                            object
actual_eta                             object
Curr_lat                              float64
Curr_lon                              float64
ontime                                 object
delay                                  object
DestinationLocation_Code               object
trip_start_date                        object
trip_end_date                          object
TRANSPORTATION_DISTANCE_IN_KM         float64
vehicleType                            object
Minimum_kms_to_be_covered_in_a_day    float64
Driver_Name                            object
customerID                             object
supplierID                             object
dtype: object

In [5]:
df = df.drop(columns=[
    'Org_lat_lon', 'Des_lat_lon', 'Curr_lat', 'Curr_lon',
    'DestinationLocation_Code', 'supplierID'
])

In [6]:
df

,BookingID,Market/Regular,BookingID_Date,vehicle_no,Origin_Location,Data_Ping_time,Planned_ETA,actual_eta,ontime,delay,trip_start_date,trip_end_date,TRANSPORTATION_DISTANCE_IN_KM,vehicleType,Minimum_kms_to_be_covered_in_a_day,Driver_Name,customerID
0,VCV00014271/082021,Regular,8/27/2020,TN30BC5917,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",40:28.0,22:22.8,8/28/2020 12:46,G,unknown,8/27/2020 16:21,unknown,103.0,unknown,250.0,RAMESH,DMREXCHEUX
1,VCV00014382/082021,Regular,8/27/2020,TN22AR2748,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",05:09.0,59:25.0,8/28/2020 16:03,G,unknown,8/27/2020 17:57,unknown,300.0,unknown,250.0,GIRI,LUTGCCHE06
2,VCV00014743/082021,Regular,8/28/2020,TN28AQ0781,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",40:31.0,48:24.5,8/28/2020 12:50,G,unknown,8/28/2020 0:47,unknown,61.0,unknown,250.0,RAVI,DMREXCHEUX
3,VCV00014744/082021,Regular,8/28/2020,TN68F1722,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",40:29.0,23:19.2,8/28/2020 14:22,G,unknown,8/28/2020 1:13,unknown,240.0,unknown,250.0,TAMIL,LUTGCCHE06
4,VCV00014749/082021,Regular,8/28/2020,TN88A4980,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",40:28.0,14:22.6,8/28/2020 13:25,G,unknown,8/28/2020 2:13,unknown,70.0,unknown,250.0,GANESH,DMREXCHEUX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,AEIBK1910732,Regular,12/30/2019,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11.0,55:49.0,1/8/2020 2:36,unknown,R,12/30/2019 18:23,1/11/2020 20:49,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3447,AEIBK2011419,Regular,1/7/2020,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50.0,09:40.0,1/8/2020 3:09,unknown,R,1/7/2020 14:56,1/10/2020 14:11,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3448,AEIBK1910132,Regular,12/26/2019,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13.0,21:20.0,1/5/2020 2:59,unknown,R,12/26/2019 19:56,1/11/2020 17:16,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3449,AEIBK1909663,Regular,12/21/2019,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13.0,00:49.0,1/2/2020 3:39,unknown,R,12/21/2019 18:48,1/11/2020 17:16,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3450,AEIBK1906955,Regular,11/30/2019,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15.0,34:27.0,12/11/2019 3:36,unknown,R,11/30/2019 15:10,1/2/2020 14:24,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [8]:
df['Origin_Location'].value_counts()

Origin_Location
Shive, Pune, Maharashtra                                    428
DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,TAMIL NADU    336
Jamalpur, Gurgaon, Haryana                                  254
Khorajnanoda, Ahmedabad, Gujarat                            217
Singaperumalkoil, Kanchipuram, Tamil Nadu                   128
                                                           ...
Indrapur, Kamrup, Assam                                       1
Jawahar Market Bhilai, Durg, Chattisgarh                      1
Gholkunda, Bankura, West Bengal                               1
Thaikkattukara, Ernakulam, Kerala                             1
Bhauti Pratappur, Kanpur Nagar, Uttar Pradesh                 1
Name: count, Length: 115, dtype: int64

In [11]:
df = df.rename(columns={
    'Market/Regular ': 'market_type',
    'BookingID_Date': 'booking_date',
    'vehicle_no': 'vehicle_id',
    'Origin_Location': 'origin',
    'Data_Ping_time': 'ping_time',
    'Planned_ETA': 'planned_eta',
    'actual_eta': 'actual_eta',
    'ontime': 'on_time',
    'trip_start_date': 'trip_start',
    'trip_end_date': 'trip_end',
    'TRANSPORTATION_DISTANCE_IN_KM': 'distance_km',
    'vehicleType': 'vehicle_type',
    'Minimum_kms_to_be_covered_in_a_day': 'min_km_per_day',
    'Driver_Name': 'driver_name',
    'customerID': 'customer_id'
})

In [12]:
df

,BookingID,market_type,booking_date,vehicle_id,origin,ping_time,planned_eta,actual_eta,on_time,delay,trip_start,trip_end,distance_km,vehicle_type,min_km_per_day,driver_name,customer_id
0,VCV00014271/082021,Regular,8/27/2020,TN30BC5917,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",40:28.0,22:22.8,8/28/2020 12:46,G,unknown,8/27/2020 16:21,unknown,103.0,unknown,250.0,RAMESH,DMREXCHEUX
1,VCV00014382/082021,Regular,8/27/2020,TN22AR2748,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",05:09.0,59:25.0,8/28/2020 16:03,G,unknown,8/27/2020 17:57,unknown,300.0,unknown,250.0,GIRI,LUTGCCHE06
2,VCV00014743/082021,Regular,8/28/2020,TN28AQ0781,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",40:31.0,48:24.5,8/28/2020 12:50,G,unknown,8/28/2020 0:47,unknown,61.0,unknown,250.0,RAVI,DMREXCHEUX
3,VCV00014744/082021,Regular,8/28/2020,TN68F1722,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",40:29.0,23:19.2,8/28/2020 14:22,G,unknown,8/28/2020 1:13,unknown,240.0,unknown,250.0,TAMIL,LUTGCCHE06
4,VCV00014749/082021,Regular,8/28/2020,TN88A4980,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",40:28.0,14:22.6,8/28/2020 13:25,G,unknown,8/28/2020 2:13,unknown,70.0,unknown,250.0,GANESH,DMREXCHEUX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,AEIBK1910732,Regular,12/30/2019,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11.0,55:49.0,1/8/2020 2:36,unknown,R,12/30/2019 18:23,1/11/2020 20:49,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3447,AEIBK2011419,Regular,1/7/2020,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50.0,09:40.0,1/8/2020 3:09,unknown,R,1/7/2020 14:56,1/10/2020 14:11,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3448,AEIBK1910132,Regular,12/26/2019,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13.0,21:20.0,1/5/2020 2:59,unknown,R,12/26/2019 19:56,1/11/2020 17:16,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3449,AEIBK1909663,Regular,12/21/2019,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13.0,00:49.0,1/2/2020 3:39,unknown,R,12/21/2019 18:48,1/11/2020 17:16,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3450,AEIBK1906955,Regular,11/30/2019,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15.0,34:27.0,12/11/2019 3:36,unknown,R,11/30/2019 15:10,1/2/2020 14:24,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [13]:
df.dtypes

BookingID          object
market_type        object
booking_date       object
vehicle_id         object
origin             object
ping_time          object
planned_eta        object
actual_eta         object
on_time            object
delay              object
trip_start         object
trip_end           object
distance_km       float64
vehicle_type       object
min_km_per_day    float64
driver_name        object
customer_id        object
dtype: object

In [14]:
df['on_time'].value_counts()

on_time
unknown    2024
G          1427
Name: count, dtype: int64

In [15]:
df['delay'].value_counts()

delay
R          2018
unknown    1433
Name: count, dtype: int64

In [16]:
df.loc[df.duplicated()]

Empty DataFrame
Columns: [BookingID, market_type, booking_date, vehicle_id, origin, ping_time, planned_eta, actual_eta, on_time, delay, trip_start, trip_end, distance_km, vehicle_type, min_km_per_day, driver_name, customer_id]
Index: []

In [20]:
df['trip_end'].value_counts('unknown')

trip_end
unknown            0.053028
2/10/2020 15:29    0.004636
8/11/2020 14:22    0.004057
2/14/2020 11:53    0.003477
8/20/2020 16:21    0.003477
                     ...
8/28/2020 9:05     0.000290
8/24/2020 17:27    0.000290
2/3/2020 16:04     0.000290
8/26/2020 11:35    0.000290
1/23/2020 10:27    0.000290
Name: proportion, Length: 2431, dtype: float64

In [21]:
df['min_km_per_day'].value_counts()

min_km_per_day
250.0    3438
275.0      13
Name: count, dtype: int64

In [22]:
print("on_time values:", df['on_time'].unique())
print("delay values:", df['delay'].unique())
print("vehicle_type values:", df['vehicle_type'].unique())

on_time values: ['G' 'unknown']
delay values: ['unknown' 'R']
vehicle_type values: ['unknown' '32 FT Single-Axle 7MT - HCV' '32 FT Multi-Axle 14MT - HCV'
 '1 MT Tata Ace (Open Body)' '24 FT SXL Container'
 '32 FT Multi-Axle MXL 18MT' '19 FT OPEN BODY 8 MT' '17 FT Container'
 '20 FT SXL Container' '1 MT Tata Ace (Closed Body)'
 '19 FT Open 7MT - MCV' '1.5 MT Pickup (Open Body)'
 '22 FT Taurus Open 16MT - HCV' '40 FT 3XL Trailer 35MT'
 '40 FT Flat Bed Multi-Axle 27MT - Trailer' '20 FT CLOSE 7MT-MCV '
 '14 FT Open - 3 MT' '1.5 MT Vehicle (Closed Body)'
 '24 / 26 FT Taurus Open 21MT - HCV' '32 FT Closed Container 15 MT'
 '20 FT Open 9MT - MCV' '40 FT Flat Bed Double-Axle 21MT - Trailer'
 '19 FT SXL Container' '17 FT Open 5MT - MCV' '22 FT Closed Container'
 'Mahindra LCV 1MT' '22 FT Open Body 16MT' '25 FT Open Body 21MT'
 '30 FT Open SXL 30MT' '26 FT Taurus Open 27MT - HCV' '32 FT Open Tarus'
 'Tata 407 Open 2MT - Mini-LCV'
 '15 FT Single-Axle 7.2MT (8.5 H) Container - HCV'
 '20 FT Closed  Container 8MT' 'Tata 407 / 14 FT Open 3MT LCV'
 '30 FT Open MXL 30MT' '24 / 26 FT  Closed Container  20MT - HCV'
 '28 FT Open Body 25MT' '40 FT Flat Bed Single-Axle 20MT - Trailer']

In [23]:
df['on_time'] = df['on_time'].map({'G': 'Y', 'unknown': 'N'})

print(df['on_time'].unique())
print(df['on_time'].value_counts())

['Y' 'N']
on_time
N    2024
Y    1427
Name: count, dtype: int64

In [24]:
df['delay'] = df['delay'].map({'R': 'Y', 'unknown': 'N'})

print(df['delay'].unique())
print(df['delay'].value_counts())

['N' 'Y']
delay
Y    2018
N    1433
Name: count, dtype: int64

In [25]:
print("on_time Y:", (df['on_time'] == 'Y').sum())
print("on_time N:", (df['on_time'] == 'N').sum())
print("\ndelay Y:", (df['delay'] == 'Y').sum())
print("delay N:", (df['delay'] == 'N').sum())

on_time Y: 1427
on_time N: 2024

delay Y: 2018
delay N: 1433

In [26]:
df['booking_date'] = pd.to_datetime(df['booking_date'], errors='coerce')

print(df['booking_date'].dtype)
print(df['booking_date'].head())
print(f"\nNull values: {df['booking_date'].isnull().sum()}")

datetime64[ns]
0   2020-08-27
1   2020-08-27
2   2020-08-28
3   2020-08-28
4   2020-08-28
Name: booking_date, dtype: datetime64[ns]

Null values: 0

In [27]:
df['actual_eta'] = pd.to_datetime(df['actual_eta'], errors='coerce')

print(df['actual_eta'].dtype)
print(df['actual_eta'].head())
print(f"\nNull values: {df['actual_eta'].isnull().sum()}")

datetime64[ns]
0   2020-08-28 12:46:00
1   2020-08-28 16:03:00
2   2020-08-28 12:50:00
3   2020-08-28 14:22:00
4   2020-08-28 13:25:00
Name: actual_eta, dtype: datetime64[ns]

Null values: 25

In [29]:
df = df.dropna(subset=['actual_eta'])

print(f"Shape after dropping nulls: {df.shape}")
print(f"Null values remaining: {df['actual_eta'].isnull().sum()}")

Shape after dropping nulls: (3426, 17)
Null values remaining: 0

In [28]:
df['trip_start'] = pd.to_datetime(df['trip_start'], errors='coerce')

print(df['trip_start'].dtype)
print(df['trip_start'].head())
print(f"\nNull values: {df['trip_start'].isnull().sum()}")

datetime64[ns]
0   2020-08-27 16:21:00
1   2020-08-27 17:57:00
2   2020-08-28 00:47:00
3   2020-08-28 01:13:00
4   2020-08-28 02:13:00
Name: trip_start, dtype: datetime64[ns]

Null values: 0

In [30]:
df.shape

(3426, 17)

In [31]:
df['trip_end'] = pd.to_datetime(df['trip_end'], format='mixed', errors='coerce')

print(df['trip_end'].dtype)
print(df['trip_end'].head())
print(f"\nNull values: {df['trip_end'].isnull().sum()}")

datetime64[ns]
0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: trip_end, dtype: datetime64[ns]

Null values: 183

C:\Users\yjany\AppData\Local\Temp\ipykernel_424\1086482366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trip_end'] = pd.to_datetime(df['trip_end'], format='mixed', errors='coerce')

In [32]:
df = df.copy()

print(df['trip_end'].head(10))
print(df['trip_end'].unique()[:5])

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
5   NaT
6   NaT
7   NaT
8   NaT
9   NaT
Name: trip_end, dtype: datetime64[ns]
<DatetimeArray>
[                'NaT', '2020-08-28 12:15:00', '2020-08-27 15:21:00',
 '2020-08-27 14:22:00', '2020-08-28 00:32:00']
Length: 5, dtype: datetime64[ns]

In [33]:
# Drop rows with null trip_end
df = df.dropna(subset=['trip_end'])

print(f"Shape after dropping nulls: {df.shape}")
print(f"Null values remaining: {df['trip_end'].isnull().sum()}")

Shape after dropping nulls: (3243, 17)
Null values remaining: 0

In [34]:
df

,BookingID,market_type,booking_date,vehicle_id,origin,ping_time,planned_eta,actual_eta,on_time,delay,trip_start,trip_end,distance_km,vehicle_type,min_km_per_day,driver_name,customer_id
140,AEIBK2027469,Regular,2020-08-26,MH14GD9464,"Shive, Pune, Maharashtra",15:10.0,03:46.0,2020-08-28 12:48:00,Y,N,2020-08-26 16:16:00,2020-08-28 12:15:00,1290.0,32 FT Multi-Axle 14MT - HCV,250.0,VIRAT NILAPALLE,DMREXCHEUX
141,VCV00014153/082021,Regular,2020-08-27,TN30BC9320,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",35:40.0,21:48.6,2020-08-28 12:13:00,Y,N,2020-08-27 15:21:00,2020-08-27 15:21:00,29.0,unknown,250.0,SENTHIL KUMAR,DMREXCHEUX
142,VCV00014063/082021,Regular,2020-08-27,TN30BB1036,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:38.0,22:17.8,2020-08-28 11:33:00,Y,N,2020-08-27 14:21:00,2020-08-27 14:22:00,21.0,unknown,250.0,ANBU,DMREXCHEUX
143,VCV00014741/082021,Regular,2020-08-28,TN88D4134,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:37.0,32:20.5,2020-08-28 11:31:00,Y,N,2020-08-28 00:31:00,2020-08-28 00:32:00,20.0,unknown,250.0,SUDHAKAR,DMREXCHEUX
144,AEIBK2027446,Regular,2020-08-26,GJ01DZ8943,"Khorajnanoda, Ahmedabad, Gujarat",35:08.0,55:08.0,2020-08-29 07:09:00,Y,N,2020-08-26 15:35:00,2020-08-28 11:21:00,1900.0,32 FT Single-Axle 7MT - HCV,250.0,MAN SINGH,FILEXCHE19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,AEIBK1910732,Regular,2019-12-30,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11.0,55:49.0,2020-01-08 02:36:00,N,Y,2019-12-30 18:23:00,2020-01-11 20:49:00,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3447,AEIBK2011419,Regular,2020-01-07,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50.0,09:40.0,2020-01-08 03:09:00,N,Y,2020-01-07 14:56:00,2020-01-10 14:11:00,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3448,AEIBK1910132,Regular,2019-12-26,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13.0,21:20.0,2020-01-05 02:59:00,N,Y,2019-12-26 19:56:00,2020-01-11 17:16:00,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3449,AEIBK1909663,Regular,2019-12-21,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13.0,00:49.0,2020-01-02 03:39:00,N,Y,2019-12-21 18:48:00,2020-01-11 17:16:00,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3450,AEIBK1906955,Regular,2019-11-30,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15.0,34:27.0,2019-12-11 03:36:00,N,Y,2019-11-30 15:10:00,2020-01-02 14:24:00,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [35]:
df['origin'].value_counts()

origin
Shive, Pune, Maharashtra                                    401
DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,TAMIL NADU    304
Jamalpur, Gurgaon, Haryana                                  238
Khorajnanoda, Ahmedabad, Gujarat                            207
Singaperumalkoil, Kanchipuram, Tamil Nadu                   120
                                                           ...
Indrapur, Kamrup, Assam                                       1
Jawahar Market Bhilai, Durg, Chattisgarh                      1
Gholkunda, Bankura, West Bengal                               1
Thaikkattukara, Ernakulam, Kerala                             1
Bhauti Pratappur, Kanpur Nagar, Uttar Pradesh                 1
Name: count, Length: 113, dtype: int64

In [41]:
df['ping_time'] = df['ping_time'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
df['planned_eta'] = df['planned_eta'].astype(str).str.replace(r'\.\d+$', '', regex=True).str.strip()

print(df['ping_time'].head())
print(df['planned_eta'].head(10))

140    15:10
141    35:40
142    25:38
143    25:37
144    35:08
Name: ping_time, dtype: object
140    03:46
141    21:48
142    22:17
143    32:20
144    55:08
145    45:33
146    14:22
147    05:12
148    57:32
149    39:48
Name: planned_eta, dtype: object

In [42]:
df['distance_km'] = df['distance_km'].round(2)
df['min_km_per_day'] = df['min_km_per_day'].round(2)

print(df['distance_km'].head())
print(df['min_km_per_day'].head())

140    1290.0
141      29.0
142      21.0
143      20.0
144    1900.0
Name: distance_km, dtype: float64
140    250.0
141    250.0
142    250.0
143    250.0
144    250.0
Name: min_km_per_day, dtype: float64

In [43]:
print(f"Unknown vehicle_type count: {(df['vehicle_type'] == 'unknown').sum()}")
print(f"Total rows: {df.shape[0]}")

Unknown vehicle_type count: 706
Total rows: 3243

In [44]:
print(f"Unique drivers: {df['driver_name'].nunique()}")
print(f"Null driver_name: {df['driver_name'].isnull().sum()}")
print(f"\nUnique customers: {df['customer_id'].nunique()}")
print(f"Null customer_id: {df['customer_id'].isnull().sum()}")

Unique drivers: 1275
Null driver_name: 0

Unique customers: 33
Null customer_id: 0

In [45]:
print(df.dtypes)
print(f"\nShape: {df.shape}")
print(f"\nNull values per column:")
print(df.isnull().sum())

BookingID                 object
market_type               object
booking_date      datetime64[ns]
vehicle_id                object
origin                    object
ping_time                 object
planned_eta               object
actual_eta        datetime64[ns]
on_time                   object
delay                     object
trip_start        datetime64[ns]
trip_end          datetime64[ns]
distance_km              float64
vehicle_type              object
min_km_per_day           float64
driver_name               object
customer_id               object
dtype: object

Shape: (3243, 17)

Null values per column:
BookingID         0
market_type       0
booking_date      0
vehicle_id        0
origin            0
ping_time         0
planned_eta       0
actual_eta        0
on_time           0
delay             0
trip_start        0
trip_end          0
distance_km       0
vehicle_type      0
min_km_per_day    0
driver_name       0
customer_id       0
dtype: int64

In [47]:
df

,BookingID,market_type,booking_date,vehicle_id,origin,ping_time,planned_eta,actual_eta,on_time,delay,trip_start,trip_end,distance_km,vehicle_type,min_km_per_day,driver_name,customer_id
140,AEIBK2027469,Regular,2020-08-26,MH14GD9464,"Shive, Pune, Maharashtra",15:10,03:46,2020-08-28 12:48:00,Y,N,2020-08-26 16:16:00,2020-08-28 12:15:00,1290.0,32 FT Multi-Axle 14MT - HCV,250.0,VIRAT NILAPALLE,DMREXCHEUX
141,VCV00014153/082021,Regular,2020-08-27,TN30BC9320,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",35:40,21:48,2020-08-28 12:13:00,Y,N,2020-08-27 15:21:00,2020-08-27 15:21:00,29.0,unknown,250.0,SENTHIL KUMAR,DMREXCHEUX
142,VCV00014063/082021,Regular,2020-08-27,TN30BB1036,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:38,22:17,2020-08-28 11:33:00,Y,N,2020-08-27 14:21:00,2020-08-27 14:22:00,21.0,unknown,250.0,ANBU,DMREXCHEUX
143,VCV00014741/082021,Regular,2020-08-28,TN88D4134,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:37,32:20,2020-08-28 11:31:00,Y,N,2020-08-28 00:31:00,2020-08-28 00:32:00,20.0,unknown,250.0,SUDHAKAR,DMREXCHEUX
144,AEIBK2027446,Regular,2020-08-26,GJ01DZ8943,"Khorajnanoda, Ahmedabad, Gujarat",35:08,55:08,2020-08-29 07:09:00,Y,N,2020-08-26 15:35:00,2020-08-28 11:21:00,1900.0,32 FT Single-Axle 7MT - HCV,250.0,MAN SINGH,FILEXCHE19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,AEIBK1910732,Regular,2019-12-30,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11,55:49,2020-01-08 02:36:00,N,Y,2019-12-30 18:23:00,2020-01-11 20:49:00,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3447,AEIBK2011419,Regular,2020-01-07,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50,09:40,2020-01-08 03:09:00,N,Y,2020-01-07 14:56:00,2020-01-10 14:11:00,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3448,AEIBK1910132,Regular,2019-12-26,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13,21:20,2020-01-05 02:59:00,N,Y,2019-12-26 19:56:00,2020-01-11 17:16:00,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3449,AEIBK1909663,Regular,2019-12-21,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13,00:49,2020-01-02 03:39:00,N,Y,2019-12-21 18:48:00,2020-01-11 17:16:00,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3450,AEIBK1906955,Regular,2019-11-30,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15,34:27,2019-12-11 03:36:00,N,Y,2019-11-30 15:10:00,2020-01-02 14:24:00,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [48]:
df = df.reset_index(drop=True)

In [49]:
df

,BookingID,market_type,booking_date,vehicle_id,origin,ping_time,planned_eta,actual_eta,on_time,delay,trip_start,trip_end,distance_km,vehicle_type,min_km_per_day,driver_name,customer_id
0,AEIBK2027469,Regular,2020-08-26,MH14GD9464,"Shive, Pune, Maharashtra",15:10,03:46,2020-08-28 12:48:00,Y,N,2020-08-26 16:16:00,2020-08-28 12:15:00,1290.0,32 FT Multi-Axle 14MT - HCV,250.0,VIRAT NILAPALLE,DMREXCHEUX
1,VCV00014153/082021,Regular,2020-08-27,TN30BC9320,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",35:40,21:48,2020-08-28 12:13:00,Y,N,2020-08-27 15:21:00,2020-08-27 15:21:00,29.0,unknown,250.0,SENTHIL KUMAR,DMREXCHEUX
2,VCV00014063/082021,Regular,2020-08-27,TN30BB1036,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:38,22:17,2020-08-28 11:33:00,Y,N,2020-08-27 14:21:00,2020-08-27 14:22:00,21.0,unknown,250.0,ANBU,DMREXCHEUX
3,VCV00014741/082021,Regular,2020-08-28,TN88D4134,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:37,32:20,2020-08-28 11:31:00,Y,N,2020-08-28 00:31:00,2020-08-28 00:32:00,20.0,unknown,250.0,SUDHAKAR,DMREXCHEUX
4,AEIBK2027446,Regular,2020-08-26,GJ01DZ8943,"Khorajnanoda, Ahmedabad, Gujarat",35:08,55:08,2020-08-29 07:09:00,Y,N,2020-08-26 15:35:00,2020-08-28 11:21:00,1900.0,32 FT Single-Axle 7MT - HCV,250.0,MAN SINGH,FILEXCHE19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,AEIBK1910732,Regular,2019-12-30,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11,55:49,2020-01-08 02:36:00,N,Y,2019-12-30 18:23:00,2020-01-11 20:49:00,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3239,AEIBK2011419,Regular,2020-01-07,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50,09:40,2020-01-08 03:09:00,N,Y,2020-01-07 14:56:00,2020-01-10 14:11:00,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3240,AEIBK1910132,Regular,2019-12-26,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13,21:20,2020-01-05 02:59:00,N,Y,2019-12-26 19:56:00,2020-01-11 17:16:00,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3241,AEIBK1909663,Regular,2019-12-21,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13,00:49,2020-01-02 03:39:00,N,Y,2019-12-21 18:48:00,2020-01-11 17:16:00,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3242,AEIBK1906955,Regular,2019-11-30,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15,34:27,2019-12-11 03:36:00,N,Y,2019-11-30 15:10:00,2020-01-02 14:24:00,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [50]:
df.to_csv("../Delivery truck trips data/delivery_trucks_cleaned.csv", index=False)

print(f"Index reset! Now starts at: {df.index[0]}")
print(df.head())

Index reset! Now starts at: 0
            BookingID market_type booking_date  vehicle_id  \
0        AEIBK2027469     Regular   2020-08-26  MH14GD9464
1  VCV00014153/082021     Regular   2020-08-27  TN30BC9320
2  VCV00014063/082021     Regular   2020-08-27  TN30BB1036
3  VCV00014741/082021     Regular   2020-08-28   TN88D4134
4        AEIBK2027446     Regular   2020-08-26  GJ01DZ8943

                                              origin ping_time planned_eta  \
0                           Shive, Pune, Maharashtra     15:10       03:46
1  DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...     35:40       21:48
2  DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...     25:38       22:17
3  DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...     25:37       32:20
4                   Khorajnanoda, Ahmedabad, Gujarat     35:08       55:08

           actual_eta on_time delay          trip_start            trip_end  \
0 2020-08-28 12:48:00       Y     N 2020-08-26 16:16:00 2020-08-28 12:15:00
1 2020-08-28 12:13:00       Y     N 2020-08-27 15:21:00 2020-08-27 15:21:00
2 2020-08-28 11:33:00       Y     N 2020-08-27 14:21:00 2020-08-27 14:22:00
3 2020-08-28 11:31:00       Y     N 2020-08-28 00:31:00 2020-08-28 00:32:00
4 2020-08-29 07:09:00       Y     N 2020-08-26 15:35:00 2020-08-28 11:21:00

   distance_km                 vehicle_type  min_km_per_day      driver_name  \
0       1290.0  32 FT Multi-Axle 14MT - HCV           250.0  VIRAT NILAPALLE
1         29.0                      unknown           250.0    SENTHIL KUMAR
2         21.0                      unknown           250.0             ANBU
3         20.0                      unknown           250.0         SUDHAKAR
4       1900.0  32 FT Single-Axle 7MT - HCV           250.0        MAN SINGH

  customer_id
0  DMREXCHEUX
1  DMREXCHEUX
2  DMREXCHEUX
3  DMREXCHEUX
4  FILEXCHE19