In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../Delivery truck trips data/delivery_trucks_cleaned.csv", low_memory=False)

In [3]:
df

,BookingID,market_type,booking_date,vehicle_id,origin,ping_time,planned_eta,actual_eta,on_time,delay,trip_start,trip_end,distance_km,vehicle_type,min_km_per_day,driver_name,customer_id
0,AEIBK2027469,Regular,2020-08-26,MH14GD9464,"Shive, Pune, Maharashtra",15:10,03:46,2020-08-28 12:48:00,Y,N,2020-08-26 16:16:00,2020-08-28 12:15:00,1290.0,32 FT Multi-Axle 14MT - HCV,250.0,VIRAT NILAPALLE,DMREXCHEUX
1,VCV00014153/082021,Regular,2020-08-27,TN30BC9320,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",35:40,21:48,2020-08-28 12:13:00,Y,N,2020-08-27 15:21:00,2020-08-27 15:21:00,29.0,unknown,250.0,SENTHIL KUMAR,DMREXCHEUX
2,VCV00014063/082021,Regular,2020-08-27,TN30BB1036,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:38,22:17,2020-08-28 11:33:00,Y,N,2020-08-27 14:21:00,2020-08-27 14:22:00,21.0,unknown,250.0,ANBU,DMREXCHEUX
3,VCV00014741/082021,Regular,2020-08-28,TN88D4134,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:37,32:20,2020-08-28 11:31:00,Y,N,2020-08-28 00:31:00,2020-08-28 00:32:00,20.0,unknown,250.0,SUDHAKAR,DMREXCHEUX
4,AEIBK2027446,Regular,2020-08-26,GJ01DZ8943,"Khorajnanoda, Ahmedabad, Gujarat",35:08,55:08,2020-08-29 07:09:00,Y,N,2020-08-26 15:35:00,2020-08-28 11:21:00,1900.0,32 FT Single-Axle 7MT - HCV,250.0,MAN SINGH,FILEXCHE19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,AEIBK1910732,Regular,2019-12-30,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11,55:49,2020-01-08 02:36:00,N,Y,2019-12-30 18:23:00,2020-01-11 20:49:00,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3239,AEIBK2011419,Regular,2020-01-07,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50,09:40,2020-01-08 03:09:00,N,Y,2020-01-07 14:56:00,2020-01-10 14:11:00,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3240,AEIBK1910132,Regular,2019-12-26,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13,21:20,2020-01-05 02:59:00,N,Y,2019-12-26 19:56:00,2020-01-11 17:16:00,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3241,AEIBK1909663,Regular,2019-12-21,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13,00:49,2020-01-02 03:39:00,N,Y,2019-12-21 18:48:00,2020-01-11 17:16:00,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3242,AEIBK1906955,Regular,2019-11-30,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15,34:27,2019-12-11 03:36:00,N,Y,2019-11-30 15:10:00,2020-01-02 14:24:00,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [4]:
df.dtypes

BookingID          object
market_type        object
booking_date       object
vehicle_id         object
origin             object
ping_time          object
planned_eta        object
actual_eta         object
on_time            object
delay              object
trip_start         object
trip_end           object
distance_km       float64
vehicle_type       object
min_km_per_day    float64
driver_name        object
customer_id        object
dtype: object

In [5]:
# ── Datetime columns ──────────────────────────────────────────────────────────
for col in ['booking_date', 'actual_eta', 'trip_start', 'trip_end']:
    df[col] = pd.to_datetime(df[col], errors='coerce')
 
# ── Category columns (low-cardinality) ───────────────────────────────────────
for col in ['market_type', 'on_time', 'delay', 'vehicle_type']:
    df[col] = df[col].astype('category')
 
# ── String / ID columns ───────────────────────────────────────────────────────
for col in ['BookingID', 'vehicle_id', 'origin', 'driver_name',
            'customer_id', 'ping_time', 'planned_eta']:
    df[col] = df[col].astype('string')
 
# ── Float columns (already correct, just confirm) ─────────────────────────────
df['distance_km']    = df['distance_km'].astype('float64')
df['min_km_per_day'] = df['min_km_per_day'].astype('float64')
 
print(df.dtypes)
print(f"\nShape: {df.shape}")

BookingID         string[python]
market_type             category
booking_date      datetime64[ns]
vehicle_id        string[python]
origin            string[python]
ping_time         string[python]
planned_eta       string[python]
actual_eta        datetime64[ns]
on_time                 category
delay                   category
trip_start        datetime64[ns]
trip_end          datetime64[ns]
distance_km              float64
vehicle_type            category
min_km_per_day           float64
driver_name       string[python]
customer_id       string[python]
dtype: object

Shape: (3243, 17)

In [7]:
df.isna().sum()

BookingID         0
market_type       0
booking_date      0
vehicle_id        0
origin            0
ping_time         0
planned_eta       0
actual_eta        0
on_time           0
delay             0
trip_start        0
trip_end          0
distance_km       0
vehicle_type      0
min_km_per_day    0
driver_name       0
customer_id       0
dtype: int64

In [8]:
df

,BookingID,market_type,booking_date,vehicle_id,origin,ping_time,planned_eta,actual_eta,on_time,delay,trip_start,trip_end,distance_km,vehicle_type,min_km_per_day,driver_name,customer_id
0,AEIBK2027469,Regular,2020-08-26,MH14GD9464,"Shive, Pune, Maharashtra",15:10,03:46,2020-08-28 12:48:00,Y,N,2020-08-26 16:16:00,2020-08-28 12:15:00,1290.0,32 FT Multi-Axle 14MT - HCV,250.0,VIRAT NILAPALLE,DMREXCHEUX
1,VCV00014153/082021,Regular,2020-08-27,TN30BC9320,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",35:40,21:48,2020-08-28 12:13:00,Y,N,2020-08-27 15:21:00,2020-08-27 15:21:00,29.0,unknown,250.0,SENTHIL KUMAR,DMREXCHEUX
2,VCV00014063/082021,Regular,2020-08-27,TN30BB1036,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:38,22:17,2020-08-28 11:33:00,Y,N,2020-08-27 14:21:00,2020-08-27 14:22:00,21.0,unknown,250.0,ANBU,DMREXCHEUX
3,VCV00014741/082021,Regular,2020-08-28,TN88D4134,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",25:37,32:20,2020-08-28 11:31:00,Y,N,2020-08-28 00:31:00,2020-08-28 00:32:00,20.0,unknown,250.0,SUDHAKAR,DMREXCHEUX
4,AEIBK2027446,Regular,2020-08-26,GJ01DZ8943,"Khorajnanoda, Ahmedabad, Gujarat",35:08,55:08,2020-08-29 07:09:00,Y,N,2020-08-26 15:35:00,2020-08-28 11:21:00,1900.0,32 FT Single-Axle 7MT - HCV,250.0,MAN SINGH,FILEXCHE19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,AEIBK1910732,Regular,2019-12-30,OD14L7676,"Garudagaon, Cuttack, Odisha",25:11,55:49,2020-01-08 02:36:00,N,Y,2019-12-30 18:23:00,2020-01-11 20:49:00,78.5,40 FT 3XL Trailer 35MT,250.0,BILAL ALI,LTLEXMUM40
3239,AEIBK2011419,Regular,2020-01-07,AP16TY1859,"Gopavarapugudem, Krishna, Andhra Pradesh",05:50,09:40,2020-01-08 03:09:00,N,Y,2020-01-07 14:56:00,2020-01-10 14:11:00,117.0,40 FT 3XL Trailer 35MT,250.0,Bharath Hanoku,LTLEXMUM40
3240,AEIBK1910132,Regular,2019-12-26,NL01D5206,"B.S.City Plant, Bokaro, Jharkhand",20:13,21:20,2020-01-05 02:59:00,N,Y,2019-12-26 19:56:00,2020-01-11 17:16:00,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,250.0,Shiv Lal Marandi,LTLEXMUM40
3241,AEIBK1909663,Regular,2019-12-21,NL01K7906,"Bokaro Steel City, Bokaro, Jharkhand",50:13,00:49,2020-01-02 03:39:00,N,Y,2019-12-21 18:48:00,2020-01-11 17:16:00,148.0,40 FT 3XL Trailer 35MT,250.0,Sunil Rajwar,LTLEXMUM40
3242,AEIBK1906955,Regular,2019-11-30,GJ15UU7437,"Changodar, Ahmedabad, Gujarat",50:15,34:27,2019-12-11 03:36:00,N,Y,2019-11-30 15:10:00,2020-01-02 14:24:00,25.0,40 FT 3XL Trailer 35MT,250.0,Mahendra Singh,LTLEXMUM40

In [6]:
df.to_csv("../Delivery truck trips data/delivery_trucks_cleaned.csv", index=False)
print("Saved successfully!")

Saved successfully!