In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import os
pd.set_option('display.max_columns', None)

In [2]:
print(os.getcwd())

C:\Users\yjany\week 4-5\notebooks

In [3]:
df = pd.read_csv("../Traffic_Violations.csv")

In [4]:
df

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,Search Conducted,Search Disposition,Search Outcome,Search Reason,Search Reason For Stop,Search Type,Search Arrest Reason,State,VehicleType,Year,Make,Model,Color,Violation Type,Charge,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
0,52282e8c-f2e1-4bb5-8509-2d5e4f8da8ca,05/01/2023,23:11:00,MCP,"3rd District, Silver Spring",OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,No,NaN,Citation,NaN,17-107(a1),NaN,NaN,MD,02 - Automobile,2007.0,CHEV,CRUZ,BLACK,Citation,13-401(b1),Transportation Article,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(0.0, 0.0)"
1,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,No,NaN,Citation,NaN,20-102(a1),NaN,NaN,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,16-101(a1),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
2,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,No,NaN,Citation,NaN,20-102(a1),NaN,NaN,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,13-409(b),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
3,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,No,NaN,Citation,NaN,20-102(a1),NaN,NaN,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,21-310(a),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
4,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,No,NaN,Citation,NaN,20-102(a1),NaN,NaN,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,21-801(b),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098622,7c8201e7-2736-48a5-9a12-f4508b79543e,03/08/2026,20:55:00,MCP,"4th District, Wheaton",DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,No,NaN,Warning,NaN,21-202(h1),NaN,NaN,MD,02 - Automobile,2024.0,TOYOTA,TUNDRA,GRAY,Warning,21-202(h1),Transportation Article,False,ASIAN,M,BURTONSVILLE,MD,MD,A - Marked Patrol,"(39.0755823333333, -77.0011893333333)"
2098623,096ecf51-1b74-4dc3-aa30-3716918cde4e,03/08/2026,15:17:00,MCP,"1st District, Rockville",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MD,02 - Automobile,2019.0,DODGE,CHALLENGER,"GREEN, LGT",Warning,13-401(h),Transportation Article,False,BLACK,M,ROCKVILLE,MD,MD,A - Marked Patrol,"(39.1065928333333, -77.1814368333333)"
2098624,b7eab6cf-5106-438f-9101-a7594b8b0f50,03/08/2026,17:29:00,MCP,"5th District, Germantown",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,118 @ AIRCRAFT DR,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MD,02 - Automobile,2009.0,VOLKSWAGEN,TOUAREG,SILVER,Warning,13-401(h),Transportation Article,False,WHITE,M,GERMANTOWN,MD,MD,A - Marked Patrol,"(0.0, 0.0)"
2098625,9952873c-c594-4c93-934b-c605847df755,03/08/2026,01:33:00,MCP,"3rd District, Silver Spring",DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,No,NaN,Warning,NaN,21-801(a),NaN,NaN,MD,02 - Automobile,2026.0,TOYOTA,COROLLA,BLACK,Warning,16-101(a1),Transportation Article,False,HISPANIC,M,LAUREL,MD,MD,A - Marked Patrol,"(39.1063653333333, -76.920828)"
2098626,f5136f74-c7d9-4aa3-b81a-dbb0850434ef,03/07/2026,23:09:00,MCP,"2nd District, Bethesda",PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,No,NaN,Warning,NaN,13-411(f),NaN,NaN,MD,02 - Automobile,2020.0,HOND,SD,GRAY,Warning,13-411(e),Transportation Article,False,OTHER,F,ROCKVILLE,MD,MD,A - Marked Patrol,"(0.0, 0.0)"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2098627 entries, 0 to 2098626
Data columns (total 43 columns):
 #   Column                   Dtype
---  ------                   -----
 0   SeqID                    object
 1   Date Of Stop             object
 2   Time Of Stop             object
 3   Agency                   object
 4   SubAgency                object
 5   Description              object
 6   Location                 object
 7   Latitude                 float64
 8   Longitude                float64
 9   Accident                 object
 10  Belts                    object
 11  Personal Injury          object
 12  Property Damage          object
 13  Fatal                    object
 14  Commercial License       object
 15  HAZMAT                   object
 16  Commercial Vehicle       object
 17  Alcohol                  object
 18  Work Zone                object
 19  Search Conducted         object
 20  Search Disposition       object
 21  Search Outcome           object
 22  Search Reason            object
 23  Search Reason For Stop   object
 24  Search Type              object
 25  Search Arrest Reason     object
 26  State                    object
 27  VehicleType              object
 28  Year                     float64
 29  Make                     object
 30  Model                    object
 31  Color                    object
 32  Violation Type           object
 33  Charge                   object
 34  Article                  object
 35  Contributed To Accident  bool
 36  Race                     object
 37  Gender                   object
 38  Driver City              object
 39  Driver State             object
 40  DL State                 object
 41  Arrest Type              object
 42  Geolocation              object
dtypes: bool(1), float64(3), object(39)
memory usage: 674.5+ MB

In [6]:
dfexe = [
    'SeqID',
    'Agency',
    'SubAgency',  
    'Search Conducted', 
    'Search Disposition',
    'Search Outcome',       
    'Search Reason',       
    'Search Reason For Stop', 
    'Search Type',         
    'Search Arrest Reason',   
    'Arrest Type',          
    'Article',              
    'Charge',             
    'Race',                 
    'Geolocation',     
    'DL State',              
    'Driver State',          
    'Driver City',
]
df = df.drop(columns=dfexe)

In [7]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Model,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007.0,CHEV,CRUZ,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024.0,TOYOTA,TUNDRA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019.0,DODGE,CHALLENGER,"GREEN, LGT",Warning,False,M
2098624,03/08/2026,17:29:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,118 @ AIRCRAFT DR,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2009.0,VOLKSWAGEN,TOUAREG,SILVER,Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026.0,TOYOTA,COROLLA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020.0,HOND,SD,GRAY,Warning,False,F

In [8]:
df.isna().sum()

Date Of Stop                   0
Time Of Stop                   0
Description                   10
Location                       5
Latitude                       0
Longitude                      0
Accident                       0
Belts                          0
Personal Injury                0
Property Damage                0
Fatal                          0
Commercial License             0
HAZMAT                         0
Commercial Vehicle             0
Alcohol                        0
Work Zone                      0
State                         59
VehicleType                    0
Year                       10661
Make                          74
Model                        223
Color                      22366
Violation Type                 0
Contributed To Accident        0
Gender                         0
dtype: int64

In [9]:
df = df.dropna(subset=['Description', 'Location', 'Make', 'Model'])

In [10]:
df = df.copy()

In [11]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Model,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007.0,CHEV,CRUZ,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024.0,TOYOTA,TUNDRA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019.0,DODGE,CHALLENGER,"GREEN, LGT",Warning,False,M
2098624,03/08/2026,17:29:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,118 @ AIRCRAFT DR,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2009.0,VOLKSWAGEN,TOUAREG,SILVER,Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026.0,TOYOTA,COROLLA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020.0,HOND,SD,GRAY,Warning,False,F

In [12]:
df['State'] = df['State'].fillna('unknown')
df['Color'] = df['Color'].fillna('unknown')
df['Year'] = df['Year'].fillna(df['Year'].median())

In [13]:
df.isnull().sum()

Date Of Stop               0
Time Of Stop               0
Description                0
Location                   0
Latitude                   0
Longitude                  0
Accident                   0
Belts                      0
Personal Injury            0
Property Damage            0
Fatal                      0
Commercial License         0
HAZMAT                     0
Commercial Vehicle         0
Alcohol                    0
Work Zone                  0
State                      0
VehicleType                0
Year                       0
Make                       0
Model                      0
Color                      0
Violation Type             0
Contributed To Accident    0
Gender                     0
dtype: int64

In [14]:
df.shape

(2098382, 25)

In [15]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Model,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007.0,CHEV,CRUZ,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024.0,TOYOTA,TUNDRA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019.0,DODGE,CHALLENGER,"GREEN, LGT",Warning,False,M
2098624,03/08/2026,17:29:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,118 @ AIRCRAFT DR,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2009.0,VOLKSWAGEN,TOUAREG,SILVER,Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026.0,TOYOTA,COROLLA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020.0,HOND,SD,GRAY,Warning,False,F

In [16]:
df['Description'].value_counts()

Description
DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC CONTROL DEVICE INSTRUCTIONS                         173860
FAILURE TO DISPLAY REGISTRATION CARD UPON DEMAND BY POLICE OFFICER                                  91880
DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGISTRATION                                              61932
DISPLAYING EXPIRED REGISTRATION PLATE ISSUED BY ANY STATE                                           60537
FAILURE OF INDIVIDUAL DRIVING ON HIGHWAY TO DISPLAY LICENSE TO UNIFORMED POLICE ON DEMAND           56353
                                                                                                    ...
RECKLESS DRIVING VEH. BY EXCEEDING POSTED SPEED LIMIT BY 30 MPH AND OVER 78/40                          1
, TAILLIGHT, STOPLIGHT, TURN SIGNAL, ID LIGHT, CLEARANCE LIGHT, MARKER LIGHT INOPERATIVE                1
OWNER PERMITTING HWY. DRIVING OF MOTOR VEH. IN VIOLATION OF ADM. ESTABLISHED SOUND LEVEL LIMITS         1
DRIVING VEH  ON HWY WITH DEVICE IMPROPERLY DISPLAYING WHITE LIGHT FROM REAR                             1
INOPERABLE HEADLIGHT                                                                                    1
Name: count, Length: 18013, dtype: int64

In [17]:
df['Make'].value_counts()

Make
TOYOTA         243453
HONDA          230005
FORD           189787
TOYT           119070
NISSAN         110554
                ...
LUCDID              1
A/R                 1
VOLKSWAGENN         1
ERC                 1
INTIFINITY          1
Name: count, Length: 4964, dtype: int64

In [18]:
print(df['Make'].value_counts().to_string())

Make
TOYOTA                  243453
HONDA                   230005
FORD                    189787
TOYT                    119070
NISSAN                  110554
HOND                     82459
BMW                      60139
CHEV                     59546
DODGE                    52946
JEEP                     49544
CHEVY                    46510
ACURA                    45959
NISS                     44923
HYUNDAI                  44456
CHEVROLET                44007
LEXUS                    34679
KIA                      33301
MERZ                     31283
MAZDA                    29920
HYUN                     29572
GMC                      27054
AUDI                     22249
SUBARU                   21126
MERCEDES                 18926
VOLK                     18623
ACUR                     17444
CHRYSLER                 15465
DODG                     13737
INFINITI                 11908
CHRY                     11842
MITS                     11840
SUBA                     11788
VOLVO                    11538
MAZD                     11009
NONE                     10710
BUICK                    10104
MITSUBISHI                9047
CADI                      8651
VOLKSWAGON                8373
VW                        8282
CADILLAC                  8131
INFI                      8078
LEXS                      8010
LINCOLN                   7113
PONTIAC                   7073
SCION                     6950
VOLKSWAGEN                6933
VOLKS                     6737
MERC                      6548
SATURN                    5916
MERCURY                   5725
LEXU                      5663
VOLV                      4842
TESLA                     4166
PONT                      3990
TOYO                      3976
MINI                      3939
LINC                      3785
BUIC                      3432
INFINITY                  3370
SUZUKI                    3241
ISUZU                     3163
RAM                       3037
LAND ROVER                2530
MERCEDEZ                  2517
SAAB                      2497
JAGUAR                    2343
MERCEDES BENZ             2197
TESL                      2162
TOY                       2047
PORSCHE                   1996
LNDR                      1586
OLDS                      1516
PORS                      1511
NISSIAN                   1457
RANGE ROVER               1431
MACK                      1366
TOYTA                     1351
INTL                      1322
SATU                      1316
HYUND                     1278
FIAT                      1274
YAMAHA                    1252
INTERNATIONAL             1204
TOYOT                     1202
ISU                       1198
CHEVORLET                 1174
OLDSMOBILE                1164
ISUZ                      1158
JAGU                      1063
LANDROVER                 1063
CHRYS                     1028
PLYMOUTH                   914
FRHT                       883
KAWASAKI                   879
SCIO                       869
GEO                        857
FREIGHTLINER               790
LEX                        783
STRN                       773
SUZI                       760
SUZU                       748
HYUNDIA                    724
HUMMER                     711
CADILAC                    690
MNNI                       642
CHRYSTLER                  642
SUB                        621
HINO                       613
MITZ                       603
PLYM                       602
MERCEDES-BENZ              594
CHEVEROLET                 552
INFIN                      497
SUBURU                     486
KENWORTH                   465
MITSU                      459
HYUNDI                     415
TOYTOA                     405
CRYSLER                    404
MASERATI                   403
TAOTAO                     395
PTRB                       374
YAMA                       360
SMART                      333
SUBU                       329
KW                         320
HYUNDA                     317
HUMM                       300
MAZADA                     291
MAZ                        288
RANG                       284
CAD                        280
BENZ                       280
TOTY                       275
KAWK                       263
HARLEY DAVIDSON            262
JAG                        256
MERZ BENZ                  254
SAA                        254
TAIZHOU                    253
NISSA                      244
HINDA                      240
PETERBUILT                 240
MINI COOPER                239
PETE                       238
PETERBILT                  237
SATR                       236
TAO TAO                    226
MAST                       222
INF                        213
TOYOYA                     211
IZUZU                      210
INFINTI                    209
THOMAS                     203
STERLING                   202
VOLKWAGON                  202
MERCEDEZ BENZ              201
FREI                       200
HYUNDAY                    197
HYNDAI                     196
HUNDAI                     194
CARR                       190
PORCHE                     189
VOLKS WAGON                187
HYUDAI                     183
TSMR                       183
MASE                       182
KENW                       180
TOTOTA                     180
UD                         178
NISAN                      174
HARLEY                     173
CHEVE                      171
CHEVEROLT                  170
INTE                       169
MER                        168
GENESIS                    167
TOYTOTA                    166
HON                        166
ZHILONG                    163
HUYN                       155
ACCURA                     154
BWM                        152
LAND                       150
HYANDAI                    149
INFINIT                    147
DUCATI                     145
CHEVERLOT                  140
FLY WING                   139
CHYSLER                    139
ALFA                       136
MADZA                      135
CHYRSLER                   134
HONA                       133
HYU                        133
TOYOA                      130
VESPA                      130
SMRT                       130
GILL                       129
HUYNDAI                    129
MB                         127
INFINI                     125
CHEVEY                     125
UNKNOWN                    124
VOLKWAGEN                  123
VOLKSWAGGON                119
MERZEDES                   117
PORSHE                     116
ACRUA                      116
FREIGHT                    113
ALFA ROMEO                 113
GENS                       113
FOR                        109
HYND                       109
HYN                        107
RANGE                      106
MIT                        106
PREM                       104
VOLSWAGON                  103
CRYS                       103
HNDA                       102
ZHEJIANG                   100
HD                         100
MERC BENZ                  100
SAT                         99
CHRYLSER                    97
GILLIG                      97
SUBURA                      95
INFINITE                    94
VOLTSWAGON                  94
HODA                        93
UNK                         92
MERCADES                    91
BENTLEY                     91
CEHVY                       90
MISTUBISHI                  89
INT                         88
SUZ                         87
TYOTA                       87
KYMCO                       85
NEW FLYER                   85
CRYSTLER                    84
MITSIBISHI                  83
INIFINITI                   83
ROV                         82
HODNA                       80
LEXIS                       80
MITSUBUSHI                  80
TOYOYTA                     78
CADDILAC                    78
TRIUMPH                     77
DUCA                        76
MAZA                        73
COOPER                      72
STER                        71
MITSUBSHI                   71
DOGE                        71
THOM                        70
TAIZHOU ZHILONG             70
HIUNDAI                     69
INIFI                       69
FOED                        69
MITTS                       68
MECURY                      66
MIFU                        65
ORION                       65
HYUNAI                      65
FERRARI                     65
XX                          64
DIDGE                       63
ZHNG                        62
WHITE                       61
TELSA                       61
NDMC                        60
VOLSWAGEN                   60
HIONDA                      60
SUZIKI                      60
VOLKSW                      59
LINCON                      59
HOMDA                       59
CHEVROLETE                  59
HYUANDI                     59
MUSTANG                     58
DAEWOO                      58
SCOOTER                     57
4S                          56
NIS                         56
INFINTY                     56
CHRISLER                    55
HOME                        54
CADILLIAC                   54
RIVIAN                      54
ZHEJIANG JIAJUE             53
CHEROLET                    53
MINNI                       52
SION                        52
TOOTA                       52
TOMOS                       51
VOLV0                       51
TOTOYA                      51
CHECY                       50
VOLKSWAGAN                  50
HUNDAY                      50
SUBAR                       50
CHVY                        49
FIRD                        49
INTER                       48
MITZUBISHI                  48
HYUNDAU                     48
LEXSUS                      48
HYUANDAI                    48
CAMRY                       47
EAGLE                       47
CHYR                        47
SUSUKI                      47
MITSHUBISHI                 47
NISSAM                      47
CHRSYLER                    47
BENT                        46
HUDSON                      46
KTM                         46
TOYATA                      46
FRT                         45
TOYORA                      45
TOYOTA SCION                44
SSR                         44
MITSUBISH                   44
WESTERN STAR                44
ZNEN                        44
BUIK                        44
NSSAN                       44
WEST                        44
HARL                        43
CRY                         43
TAIZ                        43
MISSAN                      43
HOMD                        43
MITUBISHI                   42
WV                          42
NISSSAN                     42
TOPB                        42
PORSH                       42
CHEVROLEY                   42
VOLS                        42
MREZ                        41
STRG                        41
SURE                        41
MADZ                        41
MERCEDS                     41
MECEDES                     41
MITIS                       40
ORD                         40
HONAD                       40
CHEVRLET                    40
WORK                        39
SABB                        39
COROLLA                     39
MIST                        39
MERCE                       38
FORK                        38
VIP                         38
ONDA                        38
MERCZ                       38
BENTLY                      37
ALTIMA                      37
JIAJUE                      37
KAWA                        37
BMX                         37
BRIM                        37
WOLKSWAGEN                  36
MD                          36
FOD                         36
STLG                        36
CADALLIC                    36
GENU                        35
ACCORD                      35
TPYOTA                      35
JONWAY                      35
VK                          35
SUBR                        35
ISZU                        34
RANGEROVER                  34
LEXUX                       34
KAW                         34
BUELL                       34
CHEY                        34
MITTSUBISHI                 34
DODGE RAM                   34
GILG                        34
TOYPTA                      34
VOKSWAGON                   33
IZU                         33
HUYUNDAI                    33
SUNNY                       33
THOMAS BUILT                32
KAWASKI                     32
FERR                        32
CHEVYROLET                  32
NISSN                       32
DOGDE                       32
NISSON                      32
FLYWING                     32
HOINDA                      31
FROD                        31
CADALIC                     31
VOVLO                       31
VOLKSWA                     31
LINCOLIN                    31
TAIZHOU ZHONGNE             30
JIAJ                        30
VOL                         30
MERCEDE                     30
HONDS                       30
LUXUS                       30
LEXAS                       30
CHRYLER                     30
EPO                         30
MITSUB                      29
KENILWORTH                  29
APOLLO                      29
PACE                        29
BWI                         29
MAD                         29
MERCED                      29
GM                          29
BUCK                        29
UTIL                        29
RIVA                        29
TOTYOTA                     29
SUBUARU                     29
COTC                        29
TRANSPRO                    29
MBENZ                       28
BNW                         28
AMC                         28
CIVIC                       28
PLYMOTH                     28
YONGFU                      28
XXX                         28
MADA                        28
TOYOTS                      28
OLDMOBILE                   28
PORSCH                      28
CADDILLAC                   28
TOYTO                       28
FRTL                        27
NNT                         27
TAO                         27
VOLKWAG                     27
BWS                         27
FTL                         27
LANR                        27
LICOLN                      27
MERECEDES                   27
LODA                        27
CHEVR                       27
MOTORCYCLE                  27
TAIWAN GOLDEN B             27
HUND                        27
CEHV                        26
ASTON MARTIN                26
TOT                         26
CHEVOLET                    26
MERCEDEES                   26
CHVROLET                    26
MOPED                       26
MITISUBISHI                 26
CAM                         26
MISS                        26
DONGFANG                    26
LAMO                        25
HUDS                        25
TOYOTOA                     25
VOKS                        25
TOMAS                       25
TEST                        25
BIGT                        25
NISAAN                      25
TPYPTA                      25
CHY                         25
KAUF                        25
POLESTAR                    24
SMAR                        24
SHANGHAI                    24
VOLKSWAG                    24
LOAD                        24
GATOR                       24
MITSUBIHI                   24
MCI                         24
CEHVROLET                   24
MERCEDEZ-BENZ               24
MOZDA                       24
JETTA                       23
BART                        23
JEP                         23
HEIL                        23
HONDA`                      23
SUBARY                      23
WSTR                        23
HYUMDAI                     23
CADIALLAC                   23
CHEVU                       23
VOLKESWAGON                 23
MAXDA                       23
ELANTRA                     23
HYUNADAI                    23
GENISIS                     23
CADILLA                     23
MERDZ                       23
PONIAC                      23
YOYOTA                      23
RAV4                        23
DAEW                        22
MASERATTI                   22
HOBDA                       22
HIUNDAY                     22
RANGE ROV                   22
HAUL                        22
NIISSAN                     22
FRIEGHTLINER                22
ASTO                        22
FLYWHEEL                    22
TOYOTO                      21
STAR                        21
CHR                         21
CRAN                        21
TOYOTA/SCION                21
HOLM                        21
CADDI                       21
SPRINTER                    21
WORKHORSE                   21
BICYCLE                     21
FRD                         21
CHEVROET                    21
WILDFIRE                    21
MZDA                        21
CARRY ON                    21
LIN                         20
BOOM                        20
BRMA                        20
GORD                        20
BASHAN                      20
KAWI                        20
LANDR                       20
TRAILER                     20
THMS                        20
XXXX                        20
00                          20
FRGHT                       20
BUEL                        20
MIITS                       20
SUBURAU                     20
LOTUS                       20
HUNDI                       20
HYUNADI                     20
LEIKE                       20
MBW                         20
VOLKW                       20
VICTORY                     20
FORDQ                       20
VULC                        20
MITSBISHI                   20
AURA                        20
TAGA                        20
UHAUL                       20
DATS                        20
RANG ROVER                  20
BAODIAO                     20
GNC                         20
VOLVA                       20
HIND                        20
JONDA                       20
CEV                         20
HONDAY                      19
MERCDES                     19
KAWSAKI                     19
TK                          19
PORC                        19
TOYITA                      19
TAOT                        19
SILVER                      19
OTHR                        19
ATV                         19
PONTAIC                     19
TOYOTSA                     19
QIANXIN                     19
KEN                         19
VOKSWAGEN                   19
BRI-MAR                     19
TOUOTA                      19
AMO                         19
GENE                        19
CADALLAC                    18
AUCRA                       18
CHE                         18
TIYT                        18
INFNITY                     18
LUCID                       18
HUN                         18
TIYITA                      18
ZHEN                        18
HYUD                        18
MTIS                        18
NISSA N                     18
TRUCK                       18
TOOYOTA                     18
LAMBO                       18
ACUA                        18
INIFITI                     18
PJ                          18
LEUS                        18
VOLO                        18
JEEF                        18
VOLKE                       17
RIDE ON                     17
CEVROLET                    17
MITSUBISSHI                 17
MRZ                         17
JEEO                        17
BLUE                        17
HYNDIA                      17
ACRA                        17
MCLAREN                     17
MISTSUBISHI                 17
OLDS MOBILE                 17
PEQU                        17
SPNR                        17
MASTER                      17
DOD                         17
MG                          17
HUYANDI                     17
HOONDA                      17
LAND ROV                    17
INFNITI                     17
HUMAN                       17
YAHMAHA                     17
BRMR                        17
JAQUAR                      17
SABARU                      17
HUY                         17
KIS                         17
CHEVT                       17
MNI                         17
2016                        16

In [19]:
df['Make'] = df['Make'].replace({
    'TOYT': 'TOYOTA',
    'VOLKSWAGENN': 'VOLKSWAGEN',
    'INTIFINITY': 'INFINITI',
    'CHEV': 'CHEVROLET',
    'MERZ': 'MERCEDES',
    'HOND': 'HONDA',
    'CHEV': 'CHERVOLET',
})

In [20]:
print(df['Make'].value_counts().to_string())

Make
TOYOTA                  362523
HONDA                   312464
FORD                    189787
NISSAN                  110554
BMW                      60139
CHERVOLET                59552
DODGE                    52946
MERCEDES                 50209
JEEP                     49544
CHEVY                    46510
ACURA                    45959
NISS                     44923
HYUNDAI                  44456
CHEVROLET                44007
LEXUS                    34679
KIA                      33301
MAZDA                    29920
HYUN                     29572
GMC                      27054
AUDI                     22249
SUBARU                   21126
VOLK                     18623
ACUR                     17444
CHRYSLER                 15465
DODG                     13737
INFINITI                 11909
CHRY                     11842
MITS                     11840
SUBA                     11788
VOLVO                    11538
MAZD                     11009
NONE                     10710
BUICK                    10104
MITSUBISHI                9047
CADI                      8651
VOLKSWAGON                8373
VW                        8282
CADILLAC                  8131
INFI                      8078
LEXS                      8010
LINCOLN                   7113
PONTIAC                   7073
SCION                     6950
VOLKSWAGEN                6934
VOLKS                     6737
MERC                      6548
SATURN                    5916
MERCURY                   5725
LEXU                      5663
VOLV                      4842
TESLA                     4166
PONT                      3990
TOYO                      3976
MINI                      3939
LINC                      3785
BUIC                      3432
INFINITY                  3370
SUZUKI                    3241
ISUZU                     3163
RAM                       3037
LAND ROVER                2530
MERCEDEZ                  2517
SAAB                      2497
JAGUAR                    2343
MERCEDES BENZ             2197
TESL                      2162
TOY                       2047
PORSCHE                   1996
LNDR                      1586
OLDS                      1516
PORS                      1511
NISSIAN                   1457
RANGE ROVER               1431
MACK                      1366
TOYTA                     1351
INTL                      1322
SATU                      1316
HYUND                     1278
FIAT                      1274
YAMAHA                    1252
INTERNATIONAL             1204
TOYOT                     1202
ISU                       1198
CHEVORLET                 1174
OLDSMOBILE                1164
ISUZ                      1158
LANDROVER                 1063
JAGU                      1063
CHRYS                     1028
PLYMOUTH                   914
FRHT                       883
KAWASAKI                   879
SCIO                       869
GEO                        857
FREIGHTLINER               790
LEX                        783
STRN                       773
SUZI                       760
SUZU                       748
HYUNDIA                    724
HUMMER                     711
CADILAC                    690
CHRYSTLER                  642
MNNI                       642
SUB                        621
HINO                       613
MITZ                       603
PLYM                       602
MERCEDES-BENZ              594
CHEVEROLET                 552
INFIN                      497
SUBURU                     486
KENWORTH                   465
MITSU                      459
HYUNDI                     415
TOYTOA                     405
CRYSLER                    404
MASERATI                   403
TAOTAO                     395
PTRB                       374
YAMA                       360
SMART                      333
SUBU                       329
KW                         320
HYUNDA                     317
HUMM                       300
MAZADA                     291
MAZ                        288
RANG                       284
CAD                        280
BENZ                       280
TOTY                       275
KAWK                       263
HARLEY DAVIDSON            262
JAG                        256
SAA                        254
MERZ BENZ                  254
TAIZHOU                    253
NISSA                      244
PETERBUILT                 240
HINDA                      240
MINI COOPER                239
PETE                       238
PETERBILT                  237
SATR                       236
TAO TAO                    226
MAST                       222
INF                        213
TOYOYA                     211
IZUZU                      210
INFINTI                    209
THOMAS                     203
VOLKWAGON                  202
STERLING                   202
MERCEDEZ BENZ              201
FREI                       200
HYUNDAY                    197
HYNDAI                     196
HUNDAI                     194
CARR                       190
PORCHE                     189
VOLKS WAGON                187
HYUDAI                     183
TSMR                       183
MASE                       182
TOTOTA                     180
KENW                       180
UD                         178
NISAN                      174
HARLEY                     173
CHEVE                      171
CHEVEROLT                  170
INTE                       169
MER                        168
GENESIS                    167
HON                        166
TOYTOTA                    166
ZHILONG                    163
HUYN                       155
ACCURA                     154
BWM                        152
LAND                       150
HYANDAI                    149
INFINIT                    147
DUCATI                     145
CHEVERLOT                  140
FLY WING                   139
CHYSLER                    139
ALFA                       136
MADZA                      135
CHYRSLER                   134
HYU                        133
HONA                       133
TOYOA                      130
SMRT                       130
VESPA                      130
HUYNDAI                    129
GILL                       129
MB                         127
CHEVEY                     125
INFINI                     125
UNKNOWN                    124
VOLKWAGEN                  123
VOLKSWAGGON                119
MERZEDES                   117
PORSHE                     116
ACRUA                      116
FREIGHT                    113
GENS                       113
ALFA ROMEO                 113
FOR                        109
HYND                       109
HYN                        107
MIT                        106
RANGE                      106
PREM                       104
CRYS                       103
VOLSWAGON                  103
HNDA                       102
HD                         100
ZHEJIANG                   100
MERC BENZ                  100
SAT                         99
GILLIG                      97
CHRYLSER                    97
SUBURA                      95
VOLTSWAGON                  94
INFINITE                    94
HODA                        93
UNK                         92
MERCADES                    91
BENTLEY                     91
CEHVY                       90
MISTUBISHI                  89
INT                         88
TYOTA                       87
SUZ                         87
KYMCO                       85
NEW FLYER                   85
CRYSTLER                    84
INIFINITI                   83
MITSIBISHI                  83
ROV                         82
LEXIS                       80
HODNA                       80
MITSUBUSHI                  80
TOYOYTA                     78
CADDILAC                    78
TRIUMPH                     77
DUCA                        76
MAZA                        73
COOPER                      72
MITSUBSHI                   71
DOGE                        71
STER                        71
THOM                        70
TAIZHOU ZHILONG             70
HIUNDAI                     69
INIFI                       69
FOED                        69
MITTS                       68
MECURY                      66
ORION                       65
FERRARI                     65
HYUNAI                      65
MIFU                        65
XX                          64
DIDGE                       63
ZHNG                        62
TELSA                       61
WHITE                       61
SUZIKI                      60
NDMC                        60
HIONDA                      60
VOLSWAGEN                   60
LINCON                      59
HOMDA                       59
VOLKSW                      59
CHEVROLETE                  59
HYUANDI                     59
DAEWOO                      58
MUSTANG                     58
SCOOTER                     57
NIS                         56
4S                          56
INFINTY                     56
CHRISLER                    55
HOME                        54
RIVIAN                      54
CADILLIAC                   54
ZHEJIANG JIAJUE             53
CHEROLET                    53
MINNI                       52
SION                        52
TOOTA                       52
TOMOS                       51
VOLV0                       51
TOTOYA                      51
SUBAR                       50
HUNDAY                      50
VOLKSWAGAN                  50
CHECY                       50
CHVY                        49
FIRD                        49
MITZUBISHI                  48
HYUANDAI                    48
HYUNDAU                     48
LEXSUS                      48
INTER                       48
CAMRY                       47
MITSHUBISHI                 47
SUSUKI                      47
CHRSYLER                    47
CHYR                        47
EAGLE                       47
NISSAM                      47
TOYATA                      46
HUDSON                      46
BENT                        46
KTM                         46
TOYORA                      45
FRT                         45
WEST                        44
WESTERN STAR                44
BUIK                        44
ZNEN                        44
MITSUBISH                   44
NSSAN                       44
TOYOTA SCION                44
SSR                         44
TAIZ                        43
CRY                         43
MISSAN                      43
HOMD                        43
HARL                        43
VOLS                        42
MITUBISHI                   42
TOPB                        42
PORSH                       42
NISSSAN                     42
WV                          42
CHEVROLEY                   42
SURE                        41
MREZ                        41
STRG                        41
MECEDES                     41
MADZ                        41
MERCEDS                     41
MITIS                       40
CHEVRLET                    40
ORD                         40
HONAD                       40
WORK                        39
SABB                        39
MIST                        39
COROLLA                     39
VIP                         38
FORK                        38
MERCE                       38
MERCZ                       38
ONDA                        38
ALTIMA                      37
BMX                         37
JIAJUE                      37
BENTLY                      37
KAWA                        37
BRIM                        37
WOLKSWAGEN                  36
MD                          36
STLG                        36
CADALLIC                    36
FOD                         36
SUBR                        35
TPYOTA                      35
JONWAY                      35
GENU                        35
VK                          35
ACCORD                      35
BUELL                       34
GILG                        34
LEXUX                       34
CHEY                        34
MITTSUBISHI                 34
KAW                         34
TOYPTA                      34
DODGE RAM                   34
RANGEROVER                  34
ISZU                        34
HUYUNDAI                    33
VOKSWAGON                   33
IZU                         33
SUNNY                       33
NISSON                      32
KAWASKI                     32
CHEVYROLET                  32
FLYWING                     32
NISSN                       32
DOGDE                       32
FERR                        32
THOMAS BUILT                32
VOVLO                       31
FROD                        31
LINCOLIN                    31
HOINDA                      31
CADALIC                     31
VOLKSWA                     31
TAIZHOU ZHONGNE             30
LUXUS                       30
LEXAS                       30
MERCEDE                     30
CHRYLER                     30
JIAJ                        30
EPO                         30
HONDS                       30
VOL                         30
KENILWORTH                  29
APOLLO                      29
RIVA                        29
BWI                         29
TOTYOTA                     29
TRANSPRO                    29
PACE                        29
MERCED                      29
BUCK                        29
SUBUARU                     29
GM                          29
MAD                         29
MITSUB                      29
COTC                        29
UTIL                        29
TOYOTS                      28
PLYMOTH                     28
CIVIC                       28
PORSCH                      28
TOYTO                       28
YONGFU                      28
OLDMOBILE                   28
XXX                         28
MBENZ                       28
CADDILLAC                   28
AMC                         28
BNW                         28
MADA                        28
VOLKWAG                     27
TAO                         27
BWS                         27
MERECEDES                   27
LANR                        27
FRTL                        27
FTL                         27
MOTORCYCLE                  27
LODA                        27
HUND                        27
LICOLN                      27
NNT                         27
CHEVR                       27
TAIWAN GOLDEN B             27
CHEVOLET                    26
CAM                         26
MISS                        26
ASTON MARTIN                26
MERCEDEES                   26
TOT                         26
MOPED                       26
CEHV                        26
DONGFANG                    26
MITISUBISHI                 26
CHVROLET                    26
TPYPTA                      25
CHY                         25
TOYOTOA                     25
TOMAS                       25
KAUF                        25
VOKS                        25
TEST                        25
BIGT                        25
HUDS                        25
NISAAN                      25
LAMO                        25
LOAD                        24
SMAR                        24
GATOR                       24
MERCEDEZ-BENZ               24
VOLKSWAG                    24
MCI                         24
CEHVROLET                   24
POLESTAR                    24
MOZDA                       24
SHANGHAI                    24
MITSUBIHI                   24
JEP                         23
YOYOTA                      23
WSTR                        23
SUBARY                      23
CADIALLAC                   23
JETTA                       23
VOLKESWAGON                 23
PONIAC                      23
MAXDA                       23
MERDZ                       23
ELANTRA                     23
BART                        23
HYUNADAI                    23
HYUMDAI                     23
CHEVU                       23
GENISIS                     23
HONDA`                      23
RAV4                        23
CADILLA                     23
HEIL                        23
HAUL                        22
RANGE ROV                   22
HOBDA                       22
FRIEGHTLINER                22
HIUNDAY                     22
ASTO                        22
MASERATTI                   22
DAEW                        22
NIISSAN                     22
FLYWHEEL                    22
HOLM                        21
CHR                         21
BICYCLE                     21
MZDA                        21
CHEVROET                    21
SPRINTER                    21
TOYOTO                      21
CRAN                        21
WORKHORSE                   21
CADDI                       21
FRD                         21
CARRY ON                    21
TOYOTA/SCION                21
WILDFIRE                    21
STAR                        21
FORDQ                       20
LOTUS                       20
MBW                         20
BUEL                        20
VOLVA                       20
KAWI                        20
VICTORY                     20
BAODIAO                     20
RANG ROVER                  20
BASHAN                      20
LANDR                       20
HIND                        20
UHAUL                       20
XXXX                        20
VOLKW                       20
JONDA                       20
TRAILER                     20
HYUNADI                     20
AURA                        20
LIN                         20
BRMA                        20
LEIKE                       20
GNC                         20
BOOM                        20
VULC                        20
TAGA                        20
FRGHT                       20
MITSBISHI                   20
00                          20
HUNDI                       20
CEV                         20
MIITS                       20
GORD                        20
THMS                        20
SUBURAU                     20
DATS                        20
SILVER                      19
TOYITA                      19
QIANXIN                     19
TAOT                        19
ATV                         19
BRI-MAR                     19
PONTAIC                     19
HONDAY                      19
KEN                         19
TOYOTSA                     19
MERCDES                     19
GENE                        19
VOKSWAGEN                   19
TOUOTA                      19
PORC                        19
OTHR                        19
AMO                         19
TK                          19
KAWSAKI                     19
LAMBO                       18
TIYITA                      18
TRUCK                       18
PJ                          18
CHE                         18
LEUS                        18
TIYT                        18
HYUD                        18
NISSA N                     18
HUN                         18
LUCID                       18
TOOYOTA                     18
CADALLAC                    18
INIFITI                     18
ZHEN                        18
JEEF                        18
INFNITY                     18
AUCRA                       18
ACUA                        18
VOLO                        18
MTIS                        18
CHEVT                       17
SABARU                      17
OLDS MOBILE                 17
HUY                         17
MITSUBISSHI                 17
SPNR                        17
HYNDIA                      17
RIDE ON                     17
CEVROLET                    17
DOD                         17
HUYANDI                     17
ACRA                        17
HOONDA                      17
PEQU                        17
MISTSUBISHI                 17
MRZ                         17
MNI                         17
BRMR                        17
MG                          17
INFNITI                     17
MASTER                      17
VOLKE                       17
JEEO                        17
YAHMAHA                     17
LAND ROV                    17
JAQUAR                      17
BLUE                        17
KIS                         17
HUMAN                       17
MCLAREN                     17
SMART CAR                   16
PORCH                       16
POINTIAC                    16
PRIUS                       16

In [21]:
brand_mapping = {
    # TOYOTA
    'TOYO': 'TOYOTA', 'TOY': 'TOYOTA', 'TOYOT': 'TOYOTA',
    'TOYTA': 'TOYOTA', 'TOYOTA SCION': 'TOYOTA', 'TOYTOA': 'TOYOTA',
    'TOYOY': 'TOYOTA', 'TOYOTS': 'TOYOTA', 'TOTY': 'TOYOTA',

    # HONDA
    'HON': 'HONDA', 'HNDA': 'HONDA', 'HINDA': 'HONDA',
    'HOONDA': 'HONDA', 'HONA': 'HONDA', 'HONDAY': 'HONDA',

    # CHEVROLET
    'CHEVY': 'CHEVROLET', 'CHERVOLET': 'CHEVROLET',
    'CHEVORLET': 'CHEVROLET', 'CHEVEROLET': 'CHEVROLET', 'CHVY': 'CHEVROLET',
    'CHEVORLETT': 'CHEVROLET', 'CHEVERLOT': 'CHEVROLET',

    # NISSAN
    'NISS': 'NISSAN', 'NISSIAN': 'NISSAN', 'NISAN': 'NISSAN',
    'NISSON': 'NISSAN', 'NISAAN': 'NISSAN', 'NISSAM': 'NISSAN',

    # BMW
    'BWM': 'BMW', 'BNW': 'BMW', 'BME': 'BMW',

    # MERCEDES
    'MERC': 'MERCEDES-BENZ', 'MERZ': 'MERCEDES-BENZ', 'MERCEDEZ': 'MERCEDES-BENZ',
    'MERCEDES BENZ': 'MERCEDES-BENZ', 'MERCEDES': 'MERCEDES-BENZ',
    'MERCEDEZ BENZ': 'MERCEDES-BENZ', 'MB': 'MERCEDES-BENZ',

    # HYUNDAI
    'HYUN': 'HYUNDAI', 'HYUND': 'HYUNDAI', 'HYUNDIA': 'HYUNDAI',
    'HYUNDAU': 'HYUNDAI', 'HYUANDAI': 'HYUNDAI', 'HUNDAI': 'HYUNDAI',
    'HYNDAI': 'HYUNDAI', 'HYUNDA': 'HYUNDAI',

    # VOLKSWAGEN
    'VOLK': 'VOLKSWAGEN', 'VW': 'VOLKSWAGEN', 'VOLKSWAGON': 'VOLKSWAGEN',
    'VOLKWAGON': 'VOLKSWAGEN', 'VOLKSWAGGON': 'VOLKSWAGEN',
    'VOLKS': 'VOLKSWAGEN', 'VOLKSWAGN': 'VOLKSWAGEN',

    # DODGE
    'DODG': 'DODGE', 'DOD': 'DODGE', 'DOGE': 'DODGE', 'DIDGE': 'DODGE',

    # CHRYSLER
    'CHRY': 'CHRYSLER', 'CHRYS': 'CHRYSLER', 'CRYSLER': 'CHRYSLER',
    'CHRYST': 'CHRYSLER', 'CHRYLER': 'CHRYSLER', 'CHRYSL': 'CHRYSLER',

    # ACURA
    'ACUR': 'ACURA', 'ACRA': 'ACURA', 'ACRUA': 'ACURA', 'ACCURA': 'ACURA',

    # SUBARU
    'SUBA': 'SUBARU', 'SUBAR': 'SUBARU', 'SUBR': 'SUBARU', 'SUBURU': 'SUBARU',
    'SUBAARU': 'SUBARU', 'SUBARAU': 'SUBARU',

    # MAZDA
    'MAZD': 'MAZDA', 'MAZ': 'MAZDA', 'MAZDA3': 'MAZDA', 'MAZDA6': 'MAZDA',
    'MAZADA': 'MAZDA', 'MADZA': 'MAZDA',

    # INFINITI
    'INFI': 'INFINITI', 'INFIN': 'INFINITI', 'INFINITY': 'INFINITI',
    'INFINI': 'INFINITI', 'INFINTI': 'INFINITI', 'INFINIT': 'INFINITI',

    # LEXUS
    'LEXS': 'LEXUS', 'LEXU': 'LEXUS', 'LEXI': 'LEXUS', 'LEX': 'LEXUS',

    # CADILLAC
    'CADI': 'CADILLAC', 'CAD': 'CADILLAC', 'CADIL': 'CADILLAC',
    'CADILAC': 'CADILLAC', 'CADDILAC': 'CADILLAC',

    # MITSUBISHI
    'MITS': 'MITSUBISHI', 'MITSU': 'MITSUBISHI', 'MITZ': 'MITSUBISHI',
    'MITSUBSHI': 'MITSUBISHI', 'MITSUB': 'MITSUBISHI',

    # PONTIAC
    'PONT': 'PONTIAC', 'PONTI': 'PONTIAC', 'PONTIC': 'PONTIAC',

    # SATURN
    'SATU': 'SATURN', 'SATR': 'SATURN', 'SATUN': 'SATURN',

    # LINCOLN
    'LINC': 'LINCOLN', 'LINCL': 'LINCOLN', 'LINCOL': 'LINCOLN',

    # BUICK
    'BUIC': 'BUICK', 'BUI': 'BUICK',

    # VOLVO
    'VOLV': 'VOLVO', 'VOLVO': 'VOLVO',

    # TESLA
    'TESL': 'TESLA', 'TSLA': 'TESLA',

    # LAND ROVER
    'LNDR': 'LAND ROVER', 'LANDROVER': 'LAND ROVER', 'LAND': 'LAND ROVER',
    'RANGE ROVER': 'LAND ROVER', 'LNDROV': 'LAND ROVER',

    # JEEP
    'JEE': 'JEEP', 'JEP': 'JEEP',

    # SCION
    'SCIO': 'SCION', 'SCI': 'SCION',

    # KIA
    'KI': 'KIA',

    # ISUZU
    'ISUZ': 'ISUZU', 'ISU': 'ISUZU',

    # SUZUKI
    'SUZI': 'SUZUKI', 'SUZU': 'SUZUKI',

    # FREIGHTLINER
    'FRHT': 'FREIGHTLINER', 'FREI': 'FREIGHTLINER', 'FRGH': 'FREIGHTLINER',
    'FREIGHT': 'FREIGHTLINER',

    # PETERBILT
    'PTRB': 'PETERBILT', 'PETE': 'PETERBILT', 'PETER': 'PETERBILT',

    # KENWORTH
    'KENW': 'KENWORTH', 'KW': 'KENWORTH',

    # PLYMOUTH
    'PLYM': 'PLYMOUTH', 'PLYR': 'PLYMOUTH',

    # HUMMER
    'HUMM': 'HUMMER',

    # PORSCHE
    'PORS': 'PORSCHE', 'PORSH': 'PORSCHE', 'PORCH': 'PORSCHE',

    # AUDI
    'AUD': 'AUDI', 'AUDI': 'AUDI',

    # JAGUAR
    'JAGU': 'JAGUAR', 'JAG': 'JAGUAR',

    # ALFA ROMEO
    'ALFA': 'ALFA ROMEO', 'ALFA ROMERO': 'ALFA ROMEO',

    # MASERATI
    'MASE': 'MASERATI', 'MAST': 'MASERATI', 'MASERATTI': 'MASERATI',

    # NONE / UNKNOWN — mark for removal
    'NONE': 'UNKNOWN', 'UNKNOWN': 'UNKNOWN', 'UNK': 'UNKNOWN',
    'N/A': 'UNKNOWN', 'NA': 'UNKNOWN', 'NONE LISTED': 'UNKNOWN',
}

df['Make'] = df['Make'].str.strip().str.upper()
df['Make'] = df['Make'].replace(brand_mapping)

In [22]:
make_counts = df['Make'].value_counts()
valid_makes = make_counts[make_counts > 10].index
df = df[df['Make'].isin(valid_makes)]

df = df[df['Make'] != 'UNKNOWN']

print(f"Rows remaining: {len(df)}")
print(df['Make'].value_counts().head(20))

Rows remaining: 2076218
Make
TOYOTA           371857
HONDA            313141
FORD             189787
NISSAN           157212
CHEVROLET        151988
HYUNDAI           76833
DODGE             66834
ACURA             63690
MERCEDES-BENZ     62393
BMW               60326
JEEP              49574
VOLKSWAGEN        49279
LEXUS             49145
MAZDA             41654
SUBARU            33506
KIA               33307
CHRYSLER          28791
GMC               27054
INFINITI          24335
AUDI              22263
Name: count, dtype: int64

In [23]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Model,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007.0,CHEVROLET,CRUZ,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,EXPLORER,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024.0,TOYOTA,TUNDRA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019.0,DODGE,CHALLENGER,"GREEN, LGT",Warning,False,M
2098624,03/08/2026,17:29:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,118 @ AIRCRAFT DR,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2009.0,VOLKSWAGEN,TOUAREG,SILVER,Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026.0,TOYOTA,COROLLA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020.0,HONDA,SD,GRAY,Warning,False,F

In [24]:
print(df['Model'].value_counts().head(50))

Model
4S            200120
TK            124327
CIVIC          77497
ACCORD         76170
CAMRY          72300
COROLLA        63114
ALTIMA         39648
4D             32381
SUV            30548
2S             28806
4DR            25744
SD             23783
CRV            22344
VN             22327
RAV4           21867
VAN            20559
UT             19349
SENTRA         17990
SONATA         17770
ELANTRA        16791
EXPLORER       15779
F150           15438
HIGHLANDER     15140
JETTA          14787
ODYSSEY        14713
SIENNA         14421
PILOT          13827
PRIUS          13752
SW             13084
MAXIMA         13034
FOCUS          11920
TL             11106
TRUCK          11044
IMPALA         10886
MALIBU         10781
MUSTANG        10571
CHARGER        10036
ESCAPE         10010
FUSION          9488
ROGUE           9384
TACOMA          8751
SILVERADO       8585
MDX             8536
SU              8126
3               8039
VERSA           7693
4RUNNER         7302
AVALON          7069
PASSAT          6739
TAHOE           6653
Name: count, dtype: int64

In [25]:
df['Model'].unique()

array(['CRUZ', 'EXPLORER', 'SONATA', ..., 'TRACK HAWK', 'XL40', 'YIGUAN'],
      dtype=object)

In [26]:
df = df.drop(columns=['Model'])

In [27]:
top_10_brands = [
    'TOYOTA', 'HONDA', 'FORD', 'NISSAN', 'CHEVROLET',
    'HYUNDAI', 'DODGE', 'BMW', 'MERCEDES-BENZ', 'JEEP'
]

df = df[df['Make'].isin(top_10_brands)]
print(f"Rows remaining: {len(df)}")
print(df['Make'].value_counts())

Rows remaining: 1499945
Make
TOYOTA           371857
HONDA            313141
FORD             189787
NISSAN           157212
CHEVROLET        151988
HYUNDAI           76833
DODGE             66834
MERCEDES-BENZ     62393
BMW               60326
JEEP              49574
Name: count, dtype: int64

In [28]:
df.to_csv("../traffic_violations_cleaned.csv", index=False)
print("Saved successfully!")

Saved successfully!

In [29]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007.0,CHEVROLET,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005.0,FORD,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098621,03/08/2026,12:34:00,FAILURE TO STOP AT STOP SIGN,NELSON ST AT ASTER BLVD,39.095892,-77.167603,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2013.0,TOYOTA,RED,Warning,False,F
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024.0,TOYOTA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019.0,DODGE,"GREEN, LGT",Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026.0,TOYOTA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020.0,HONDA,GRAY,Warning,False,F

In [30]:
df['Year'] = df['Year'].astype(int)

In [31]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007,CHEVROLET,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098621,03/08/2026,12:34:00,FAILURE TO STOP AT STOP SIGN,NELSON ST AT ASTER BLVD,39.095892,-77.167603,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2013,TOYOTA,RED,Warning,False,F
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.075582,-77.001189,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024,TOYOTA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.106593,-77.181437,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019,DODGE,"GREEN, LGT",Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.106365,-76.920828,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026,TOYOTA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.000000,0.000000,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020,HONDA,GRAY,Warning,False,F

In [32]:
pd.set_option('display.precision', 2)

In [33]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007,CHEVROLET,BLACK,Citation,False,M
1,08/31/2023,16:41:00,DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
2,08/31/2023,16:41:00,FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
3,08/31/2023,16:41:00,DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
4,08/31/2023,16:41:00,FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098621,03/08/2026,12:34:00,FAILURE TO STOP AT STOP SIGN,NELSON ST AT ASTER BLVD,39.10,-77.17,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2013,TOYOTA,RED,Warning,False,F
2098622,03/08/2026,20:55:00,DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED ...,RANDOLPH RD / BREGMAN RD,39.08,-77.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024,TOYOTA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,1380 PICCARD DR,39.11,-77.18,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019,DODGE,"GREEN, LGT",Warning,False,M
2098625,03/08/2026,01:33:00,DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUI...,EB 198 & DINO DR,39.11,-76.92,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026,TOYOTA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRE...,CONNECTICUT AVE AT BRANDYWINE ST,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020,HONDA,GRAY,Warning,False,F

In [34]:
print(df['Description'].value_counts().to_string())

Description
DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC CONTROL DEVICE INSTRUCTIONS                                      125473
FAILURE TO DISPLAY REGISTRATION CARD UPON DEMAND BY POLICE OFFICER                                               66168
DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGISTRATION                                                           44008
DISPLAYING EXPIRED REGISTRATION PLATE ISSUED BY ANY STATE                                                        42182
FAILURE OF INDIVIDUAL DRIVING ON HIGHWAY TO DISPLAY LICENSE TO UNIFORMED POLICE ON DEMAND                        40899
DRIVER USING HANDS TO USE HANDHELD TELEPHONE WHILEMOTOR VEHICLE IS IN MOTION                                     37091
DRIVER FAILURE TO STOP AT STOP SIGN LINE                                                                         32857
EXCEEDING THE POSTED SPEED LIMIT OF 40 MPH                                                                       32189
EXCEEDING THE POSTED SPEED LIMIT OF 35 MPH                                                                       30553
DRIVING VEHICLE ON HIGHWAY WITHOUT CURRENT REGISTRATION PLATES AND VALIDATION TABS                               27145
PERSON DRIVING MOTOR VEHICLE ON HIGHWAY OR PUBLIC USE PROPERTY ON SUSPENDED LICENSE AND PRIVILEGE                26348
EXCEEDING THE POSTED SPEED LIMIT OF 30 MPH                                                                       24161
NEGLIGENT DRIVING VEHICLE IN CARELESS AND IMPRUDENT MANNER ENDANGERING PROPERTY, LIFE AND PERSON                 21991
STOP LIGHTS (*)                                                                                                  21286
FAILURE OF VEH. ON HWY. TO DISPLAY LIGHTED LAMPS, ILLUMINATING DEVICE IN UNFAVORABLE VISIBILITY COND             20768
DRIVER CHANGING LANES WHEN UNSAFE                                                                                20620
DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUIRED LICENSE AND AUTHORIZATION                                      19971
DRIVING VEHICLE WHILE UNDER THE INFLUENCE OF ALCOHOL                                                             19107
DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED SIGNAL                                                             17998
FAILURE TO CONTROL VEHICLE SPEED ON HIGHWAY TO AVOID COLLISION                                                   15555
OPERATING VEHICLE ON HIGHWAY WITH UNAUTHORIZED WINDOW TINTING MATERIAL                                           15416
DRIVING VEH. W/O ADEQUATE REAR REG. PLATE ILLUMINATION                                                           15188
FAILURE TO ATTACH VEHICLE REGISTRATION PLATES AT FRONT AND REAR                                                  15183
FAILURE TO STOP AT STOP SIGN                                                                                     15141
FAILURE OF LICENSEE TO NOTIFY ADMINISTRATION OF CHANGE OF ADDRESS WITHIN 30 DAYS                                 15135
FAILURE TO DISPLAY TWO LIGHTED FRONT LAMPS WHEN REQUIRED                                                         15001
DRIVER FAIL TO STOP AT FLASHING RED TRAFFIC SIGNAL STOP LINE                                                     14601
OPERATOR NOT RESTRAINED BY SEATBELT                                                                              13201
DRIVING VEH. ON HWY. W/O REQUIRED MINIMUM EQUIPMENT                                                              12709
DRIVING VEHICLE IN EXCESS OF REASONABLE AND PRUDENT SPEED ON HIGHWAY                                             11933
FAILURE TO DRIVE VEHICLE ON RIGHT HALF OF ROADWAY WHEN REQUIRED                                                  11276
DRIVING WHILE IMPAIRED BY ALCOHOL                                                                                11055
DRIVER ENTERING INTERSECTION AT FLASHING RED TRAFFIC SIGNAL WITHOUT STOPPING                                     11017
FAILURE TO EQUIP VEH. WITH REQUIRED REAR STOP LAMP                                                               10894
EXCEEDING THE POSTED SPEED LIMIT OF 55 MPH                                                                       10624
DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITHOUT REQUIRED LICENSE AND AUTHORIZATION                             10536
RECKLESS DRIVING VEHICLE IN WANTON AND WILLFUL DISREGARD FOR SAFETY OF PERSONS AND PROPERTY                      10284
OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY                                                                   9993
EXCEEDING THE POSTED SPEED LIMIT OF 45 MPH                                                                        9529
KNOWINGLY DRIVING UNINSURED VEHICLE                                                                               9021
HEADLIGHTS (*)                                                                                                    8992
EXCEEDING MAXIMUM SPEED: 39 MPH IN A POSTED 30 MPH ZONE                                                           8963
DRIVING VEH. WHILE IMPAIRED BY ALCOHOL                                                                            8536
WINDOW TINT                                                                                                       8251
PERSON DRIVING MOTOR VEHICLE WHILE LICENSE SUSPENDED UNDER 17-106, 26-204, 26-206, 27-103                         7565
DRIVING UNDER THE INFLUENCE OF ALCOHOL PER SE                                                                     7441
DRIVER WHEN TURNING LEFT FAIL TO YIELD RIGHT OF WAY TO VEHICLE APPROACHING FROM OPPOSITE DIRECTION                7368
HOLDER OF LEARNER'S PERMIT DRIVING W/O REQ. SUPERVISION                                                           7076
DRIVER FAILURE TO OBEY DESIGNATED LANE DIRECTIONS                                                                 6916
DRIVER FAIL TO STOP AT RED TRAFFIC SIGNAL BEFORE RIGHT TURN                                                       6535
OPER. MOTOR VEH. WITH OPERATOR NOT RESTRAINED BY SEAT BELT                                                        6434
PERSON DRIVING MOTOR VEHICLE ON HIGHWAY OR PUBLIC USE PROPERTY ON REVOKED LICENSE AND PRIVILEGE                   6217
DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOSER THAN REASONABLE AND PRUDENT                                      6181
POSSESSING SUSPENDED LIC.                                                                                         6125
EXCEEDING THE POSTED SPEED LIMIT OF 25 MPH                                                                        5869
DRIVING WHILE LIC. SUSP. UNDER 16-203, 16-206A2 FAIL TO ATTEND DIP, 17-106, 26-204/206, 27-103                    5848
FAILURE TO PROPERLY EQUIP & LOCATE HEADLAMPS ON MOTOR VEH.                                                        5791
PARKING WHERE PROHIBITED BY OFFICIAL SIGNS                                                                        5754
EXCEEDING MAXIMUM SPEED: 44 MPH IN A POSTED 35 MPH ZONE                                                           5297
EXCEEDING MAXIMUM SPEED: 49 MPH IN A POSTED 40 MPH ZONE                                                           5234
UNAUTHORIZED DISPLAY AND USE OF REGISTRATION PLATE                                                                4932
EXCEEDING POSTED MAXIMUM SPEED LIMIT: 44 MPH IN A POSTED 35 MPH ZONE                                              4895
FAILURE TO DISPLAY TAB ON PLATES OF VEH. AS REQUIRED BY ADM.                                                      4873
PERSON DRIVING MOTOR VEHICLE WHILE LICENSE SUSPENDED UNDER TR 17-106, 26-204, 26-206, 27-103                      4852
DRIVING VEHICLE WHILE UNDER THE INFLUENCE OF ALCOHOL PER SE                                                       4758
DRIVER FAILURE TO STOP FOR PEDESTRIAN IN CROSSWALK                                                                4653
TAILLIGHTS (*)                                                                                                    4630
DRIVING, ATTEMPTING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITHOUT REQUIRED LICENSE AND AUTHORIZATION                  4383
FAILURE TO DISPLAY & REFLECT RED COLOR LIGHT ON REAR LAMPS AND REFLECTORS AS REQ.                                 4210
TAG LIGHTS (*)                                                                                                    4205
DRIVING VEHICLE IN EXCESS OF REASONABLE AND PRUDENT SPEED ON HIGHWAY SPEED                                        4171
FAILING TO SECURE CHILD UNDER AGE 8 IN CHILD SAFETY SEAT WHEN TRANSPORTING IN MOTOR VEHICLE                       4161
FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID COLLISION                                                          4155
Stop Lights (*)                                                                                                   4049
MOTOR VEH. W/O REQUIRED STOP LAMPS EQUIPMENT                                                                      3934
DRIVING ON HWY. WITH OBSTRUCTED WINDSHIELD VIEW                                                                   3912
EXCEEDING POSTED MAXIMUM SPEED LIMIT: 49 MPH IN A POSTED 40 MPH ZONE                                              3863
FAILURE OF DR. TO MAKE LANE CH. TO AVAIL. LANE NOT IMMED. ADJ TO STOPPED, STANDING, PARKED VEH.                   3755
FAILURE OF DR. TO MAKE LANE CHANGE TO AVAIL. LANE NOT IMMED. ADJ. TO STOPPED EMERG. VEH                           3730
FAILURE OF MV OPER TO PRESENT EVIDENCE OF REQUIRED SECURITY ON REQUEST OF A LAW ENFORCEMENT OFFICER               3699
FAILURE VEH. TO YIELD INTERSECTION RIGHT-OF-WAY TO ANOTHER VEH.                                                   3650
DRIVER FAIL TO STOP AT STEADY RED ARROW SIGNAL                                                                    3489
DRIVING VEHICLE ON HIGHWAY WITH AN EXPIRED LICENSE                                                                3358
PERSON DRIVING MOTOR VEHICLE ON HIGHWAY OR PUBLIC USE PROPERTY ON SUSPENDED OUT-OF-STATE LICENSE                  3338
FAILURE TO MAINTAIN LEGIBLE REGISTRATION PLATE FREE FROM COVERS                                                   3272
DRIVER FAILING TO GIVE TURN SIGNAL CONTINUOUSLY DURING LAST 100' OF TRAVEL BEFORE TURNING                         3265
FAILURE TO ATTACH VEH. REG. PLATES AT FRONT AND REAR                                                              3125
PERMITTING VEH. TO BE DRIVEN ON HWY. W/O CURRENT REGISTRATION & VALIDATION TABS ISSUED BY ADM.                    3121
EXCEEDING THE POSTED SPEED LIMIT OF 50 MPH                                                                        3094
EXCEEDING MAXIMUM SPEED: 64 MPH IN A POSTED 55 MPH ZONE                                                           3068
DRIVING VEHICLE IN HOV LANE WHEN NOT AUTHORIZED BY TRAFFIC CONTROL DEVICE                                         2989
EXCEEDING POSTED MAXIMUM SPEED LIMIT: 39 MPH IN A POSTED 30 MPH ZONE                                              2650
DISPLAY SUSPENDED LIC.                                                                                            2623
FAILURE OF DRIVER TO DRIVE TO CURB UPON SIGNAL BY POLICE VEH.                                                     2561
FAILURE OF VEH. DRIVER INVOLVED IN ACCIDENT TO GIVE INSURANCE POLICY INFORMATION                                  2550
DRIVING WRONG WAY--ONE WAY STREET                                                                                 2512
DRIVING VEHICLE IN VIOLATION OF RESTRICTED LICENSE REQUIREMENT                                                    2439
DRIVER FAIL TO MAKE REQUIRED STOP AT SIGN                                                                         2392
RT. TURN FROM IMPROPER ROAD POSITION                                                                              2313
DRIVING VEH. ON HWY. WITH UNPAID REGISTRATION FEE                                                                 2276
DRIVING UNSAFE VEH. ON HWY.                                                                                       2195
WILLFULLY DRIVING MOTOR VEH. AT SLOW SPEED IMPEDING NORMAL AND REASONABLE TRAFFIC MOVEMENT                        2067
OWNER FAILURE TO MAINTAIN REQUIRED SECURITY FOR VEH. DURING REG. PERIOD                                           1989
Stop Lights                                                                                                       1952
DRIVE ACROSS PRIVATE PROPERTY FOR THE PURPOSE OF AVOIDING TRAFFIC CONTROL DEVICE                                  1909
GLASS (*)                                                                                                         1905
DRIVING A MOTOR VEH WITHOUT A VALID MEDICAL EXAMINERS CERTIFICATE IN POSSESSION                                   1880
FAILURE TO SECURELY FASTEN REGISTRATION PLATE TO VEHICLE                                                          1871
FAILURE TO NOTIFY ADM. OF ADDRESS CHANGE WITHIN 30 DAYS                                                           1853
EXCEEDING THE POSTED SPEED LIMIT OF 60 MPH                                                                        1846
FAILURE YIELD RIGHT OF WAY ON LEFT TURN                                                                           1814
DRIVER FAIL TO STOP AT STEADY CIRCULAR RED SIGNAL                                                                 1799
PASSENGER AGE 16 OR MORE IN OUTBOARD FRONT SEAT OF MOTOR VEHICLE WITHOUT SEATBELT RESTRAINT                       1788
Headlights (*)                                                                                                    1784
LEFT TURN FROM IMPROPER ROAD POSITION                                                                             1704
DRIVER WRITING,SENDING,READING A TEXT,ELECTRONIC MSG. WHILE OPER. VEH. IN TRAVEL PORTION OF HWY                   1673
CAUSING STANDING VEH. TO OBSTRUCT FREE VEH. PASSAGE OF ROADWAY                                                    1657
EXCEEDING MAXIMUM SPEED: 34 MPH IN A POSTED 25 MPH ZONE                                                           1602
DRIVING OFF ROADWAY WHILE PASSING VEHICLE                                                                         1556
DISPLAYING REG. PLATE ISSUED FOR OTHER VEHICLE                                                                    1542
FAILURE OF DR. TO MAKE LANE CHANGE TO AVAIL. LANE NOT IMMED. ADJ. TO STOPPED EMERG. VEH,                          1532
UNSAFE LANE CHANGING                                                                                              1522
HOLDER OF LEARNER'S PERMIT DRIVING WITH UN- AUTHORIZED PERSON OCCUPYING FRONT SEAT                                1521
UNSAFE BACKING OF MOTOR VEH.                                                                                      1497
DRIVING A VEHICLE WHILE A REMOVABLE WINDSHIELD PLACARD IS HANGING FROM THE INSIDE REARVIEW MIRROR                 1495
DRIVING VEH. WHILE WEARING EARPHONES                                                                              1454
FAILURE TO DRIVE RIGHT OF CENTER                                                                                  1450
FAILURE TO RETURN TO & REMAIN AT SCENE OF ACCIDENTINVOLVING ATTENDED VEH.DAMAGE                                   1407
FAILURE TO STOP FOR STOPPED SCHOOL VEH. OPERATING ALTERNATELY FLASHING RED LIGHTS                                 1383
DRIVER FAILING TO MAKE LEFT TURN FROM LEFT TURN LANE                                                              1366
EXCEEDING MAXIMUM SPEED: 54 MPH IN A POSTED 45 MPH ZONE                                                           1360
EXCEEDING POSTED MAXIMUM SPEED LIMIT: 64 MPH IN A POSTED 55 MPH ZONE                                              1354
DRIVER TURNING VEHICLE WITHOUT GIVING APPROPRIATE SIGNAL AS REQUIRED                                              1344
FAILURE TO MAINTAIN LEGIBLE REGISTRATION PLATE FREE FROM FOREIGN MATERIALS                                        1322
DRIVER ENTERING CROSSWALK AT FLASHING RED TRAFFIC SIGNAL WITHOUT STOPPING                                         1308
DRIVING MOTOR VEHICLE OFF ROADWAY WHILE PASSING VEHICLE                                                           1277
Window Tint                                                                                                       1265
STOPPING VEH. ON CROSSWALK                                                                                        1241
PARKING VEH. WHERE PROHIBITED BY OFFICIAL SIGN                                                                    1208
PASSENGER AGE 16 OR MORE IN REAR SEAT OF MOTOR VEH WITHOUT SEATBELT RESTRAINT                                     1154
FAILURE TO CARRY REGISTRATION CARD WITHIN VEHICLE                                                                 1129
Tag Lights (*)                                                                                                    1122
DRIVING  MOTOR VEHICLE ON HIGHWAY WITHOUT REQUIRED LICENSE AND AUTHORIZATION                                      1090
EXCEEDING HIGHWAY WORK ZONE SPEED LIMIT                                                                           1089
FAILURE TO EQUIP VEH. WITH REQ. REAR RED STOP LAMPVISIBLE FROM A DISTANCE OF NOT LESS THAN 300 FT                 1085
MOTOR VEH. MFR. AFTER JUNE 1, 1971, W/O ADEQUATE TAIL LAMPS                                                       1068
PERSON DRIVING MOTOR VEHICLE ON HIGHWAY OR PUBLIC USE PROPERTY ON REVOKED OUT-OF-STATE LICENSE                    1046
FAILURE OF MV OPER. DRIVING ON HWY TO BE IN POSS.OF, CARRY IN MV EVID. OF REQ'D SECURITY FOR MV                   1002
DRIVER MAKING IMPROPER TURN AT INTERSECTION                                                                        995
OCCUPANT UNDER 16 NOT RESTRAINED BY SEATBELT                                                                       987
FAILURE TO MAINTAIN LEGIBLE REGISTRATION PLATE FREE FROM FOREIGN MATERIALS, COVERS                                 983
EXCEEDING MAXIMUM SPEED: 45 MPH IN A POSTED 30 MPH ZONE                                                            974
Headlights                                                                                                         968
DRIVER FAILURE TO AVOID PROJECTING GLARING LIGHT WITHIN 500 FEET OF APPROACHING VEH. DRIVER                        965
Taillights (*)                                                                                                     951
STOPLIGHT INOPERATIVE                                                                                              943
FAILURE OF DRIVER TO MAKE LANE CHANGE TO AVAILABLELANE NOT IMMED. ADJACENT TO STOPPED EMERG. VEH.                  937
FAILURE TO STOP WHEN ENTERING HIGHWAY                                                                              935
EXCEEDING MAXIMUM SPEED: 59 MPH IN A POSTED 40 MPH ZONE                                                            934
FOLLOWING VEH. TOO CLOSELY                                                                                         929
FAILURE TO STOP AFTER ACCIDENT INVOLVING DAMAGE TO ATTENDED VEH.                                                   895
EXHAUST SYSTEM                                                                                                     862
EXCEEDING POSTED MAXIMUM SPEED LIMIT: 54 MPH IN A POSTED 45 MPH ZONE                                               860
DRIVING VEH. ON HWY WITH LAMP IMPROPERLY DISPLAYING WHITE LIGHT FROM REAR                                          855
DRIVER FAILURE TO REDUCE LIGHT DISTRIBUTION WHEN WITHIN 300 FEET OF APPROACHING VEH. FROM REAR                     840
INSTALLING WINDOW TINTING MATERIAL NOT IN COMPLIANCE WITH REQUIREMENTS                                             830
FAILURE TO EQUIP HWY. VEH. WITH REQUIRED LAMPS AND REFLECTORS                                                      821

In [35]:
def categorize_violation(desc):
    desc = str(desc).upper()
    if 'SPEED' in desc or 'MPH' in desc:
        return 'SPEEDING'
    elif 'ALCOHOL' in desc or 'IMPAIRED' in desc or 'INFLUENCE' in desc or 'DUI' in desc:
        return 'DUI'
    elif 'SUSPENDED' in desc or 'REVOKED' in desc or 'LICENSE' in desc:
        return 'LICENSE_ISSUE'
    elif 'STOP' in desc or 'RED' in desc or 'SIGNAL' in desc or 'TRAFFIC CONTROL' in desc:
        return 'TRAFFIC_SIGNAL'
    elif 'REGISTRATION' in desc or 'PLATES' in desc or 'UNREGISTERED' in desc:
        return 'REGISTRATION'
    elif 'SEATBELT' in desc or 'SEAT BELT' in desc or 'RESTRAINED' in desc:
        return 'SEATBELT'
    elif 'PHONE' in desc or 'HANDHELD' in desc or 'TEXT' in desc:
        return 'DISTRACTED_DRIVING'
    elif 'RECKLESS' in desc or 'NEGLIGENT' in desc or 'CARELESS' in desc:
        return 'RECKLESS_DRIVING'
    elif 'LANE' in desc or 'TURN' in desc:
        return 'IMPROPER_LANE_USE'
    elif 'HEADLIGHT' in desc or 'LAMP' in desc or 'LIGHT' in desc:
        return 'EQUIPMENT_VIOLATION'
    else:
        return 'OTHER'

# Apply and replace Description
df['Description'] = df['Description'].apply(categorize_violation)

# Check the results
print(df['Description'].value_counts())

Description
TRAFFIC_SIGNAL         460966
SPEEDING               259355
LICENSE_ISSUE          215928
OTHER                  157104
REGISTRATION           134394
EQUIPMENT_VIOLATION     64058
DUI                     56004
IMPROPER_LANE_USE       50833
DISTRACTED_DRIVING      42463
RECKLESS_DRIVING        32868
SEATBELT                25972
Name: count, dtype: int64

In [36]:
df.shape

(1499945, 24)

In [37]:
df

,Date Of Stop,Time Of Stop,Description,Location,Latitude,Longitude,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol,Work Zone,State,VehicleType,Year,Make,Color,Violation Type,Contributed To Accident,Gender
0,05/01/2023,23:11:00,TRAFFIC_SIGNAL,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007,CHEVROLET,BLACK,Citation,False,M
1,08/31/2023,16:41:00,LICENSE_ISSUE,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
2,08/31/2023,16:41:00,REGISTRATION,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
3,08/31/2023,16:41:00,OTHER,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
4,08/31/2023,16:41:00,SPEEDING,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098621,03/08/2026,12:34:00,TRAFFIC_SIGNAL,NELSON ST AT ASTER BLVD,39.10,-77.17,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2013,TOYOTA,RED,Warning,False,F
2098622,03/08/2026,20:55:00,TRAFFIC_SIGNAL,RANDOLPH RD / BREGMAN RD,39.08,-77.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024,TOYOTA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,LICENSE_ISSUE,1380 PICCARD DR,39.11,-77.18,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019,DODGE,"GREEN, LGT",Warning,False,M
2098625,03/08/2026,01:33:00,LICENSE_ISSUE,EB 198 & DINO DR,39.11,-76.92,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026,TOYOTA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,REGISTRATION,CONNECTICUT AVE AT BRANDYWINE ST,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020,HONDA,GRAY,Warning,False,F

In [38]:
df.columns.tolist()

['Date Of Stop',
 'Time Of Stop',
 'Description',
 'Location',
 'Latitude',
 'Longitude',
 'Accident',
 'Belts',
 'Personal Injury',
 'Property Damage',
 'Fatal',
 'Commercial License',
 'HAZMAT',
 'Commercial Vehicle',
 'Alcohol',
 'Work Zone',
 'State',
 'VehicleType',
 'Year',
 'Make',
 'Color',
 'Violation Type',
 'Contributed To Accident',
 'Gender']

In [39]:
df = df.rename(columns={
    'Date Of Stop': 'date_of_stop',
    'Time Of Stop': 'time_of_stop',
    'Description': 'description',
    'Location': 'location',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Accident': 'accident',
    'Belts': 'belts',
    'Personal Injury': 'personal_injury',
    'Property Damage': 'property_damage',
    'Fatal': 'fatal',
    'Commercial License': 'commercial_license',
    'HAZMAT': 'hazmat',
    'Commercial Vehicle': 'commercial_vehicle',
    'Alcohol': 'alcohol',
    'Work Zone': 'work_zone',
    'State': 'state',
    'VehicleType': 'vehicle_type',
    'Year': 'year',
    'Make': 'make',
    'Color': 'color',
    'Violation Type': 'violation_type',
    'Contributed To Accident': 'contributed_to_accident',
    'Gender': 'gender'
})

In [40]:
df

,date_of_stop,time_of_stop,description,location,latitude,longitude,accident,belts,personal_injury,property_damage,fatal,commercial_license,hazmat,commercial_vehicle,alcohol,work_zone,state,vehicle_type,year,make,color,violation_type,contributed_to_accident,gender
0,05/01/2023,23:11:00,TRAFFIC_SIGNAL,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007,CHEVROLET,BLACK,Citation,False,M
1,08/31/2023,16:41:00,LICENSE_ISSUE,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
2,08/31/2023,16:41:00,REGISTRATION,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
3,08/31/2023,16:41:00,OTHER,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
4,08/31/2023,16:41:00,SPEEDING,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098621,03/08/2026,12:34:00,TRAFFIC_SIGNAL,NELSON ST AT ASTER BLVD,39.10,-77.17,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2013,TOYOTA,RED,Warning,False,F
2098622,03/08/2026,20:55:00,TRAFFIC_SIGNAL,RANDOLPH RD / BREGMAN RD,39.08,-77.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024,TOYOTA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,LICENSE_ISSUE,1380 PICCARD DR,39.11,-77.18,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019,DODGE,"GREEN, LGT",Warning,False,M
2098625,03/08/2026,01:33:00,LICENSE_ISSUE,EB 198 & DINO DR,39.11,-76.92,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026,TOYOTA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,REGISTRATION,CONNECTICUT AVE AT BRANDYWINE ST,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020,HONDA,GRAY,Warning,False,F

In [41]:
df = df.rename(columns={
    'Date Of Stop': 'date_of_stop',
    'Time Of Stop': 'time_of_stop',
    'Description': 'description',
    'Location': 'location',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Accident': 'accident',
    'Belts': 'belts',
    'Personal Injury': 'personal_injury',
    'Property Damage': 'property_damage',
    'Fatal': 'fatal',
    'Commercial License': 'commercial_license',
    'HAZMAT': 'hazmat',
    'Commercial Vehicle': 'commercial_vehicle',
    'Alcohol': 'alcohol',
    'Work Zone': 'work_zone',
    'State': 'state',
    'VehicleType': 'vehicle_type',
    'Year': 'year',
    'Make': 'make',
    'Color': 'color',
    'Violation Type': 'violation_type',
    'Contributed To Accident': 'contributed_to_accident',
    'Gender': 'gender'
})

In [42]:
df

,date_of_stop,time_of_stop,description,location,latitude,longitude,accident,belts,personal_injury,property_damage,fatal,commercial_license,hazmat,commercial_vehicle,alcohol,work_zone,state,vehicle_type,year,make,color,violation_type,contributed_to_accident,gender
0,05/01/2023,23:11:00,TRAFFIC_SIGNAL,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2007,CHEVROLET,BLACK,Citation,False,M
1,08/31/2023,16:41:00,LICENSE_ISSUE,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
2,08/31/2023,16:41:00,REGISTRATION,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
3,08/31/2023,16:41:00,OTHER,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
4,08/31/2023,16:41:00,SPEEDING,OAKMONT AVE @ GROVEMONT CIR,39.10,-77.15,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2005,FORD,BLACK,Citation,False,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098621,03/08/2026,12:34:00,TRAFFIC_SIGNAL,NELSON ST AT ASTER BLVD,39.10,-77.17,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2013,TOYOTA,RED,Warning,False,F
2098622,03/08/2026,20:55:00,TRAFFIC_SIGNAL,RANDOLPH RD / BREGMAN RD,39.08,-77.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2024,TOYOTA,GRAY,Warning,False,M
2098623,03/08/2026,15:17:00,LICENSE_ISSUE,1380 PICCARD DR,39.11,-77.18,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2019,DODGE,"GREEN, LGT",Warning,False,M
2098625,03/08/2026,01:33:00,LICENSE_ISSUE,EB 198 & DINO DR,39.11,-76.92,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2026,TOYOTA,BLACK,Warning,False,M
2098626,03/07/2026,23:09:00,REGISTRATION,CONNECTICUT AVE AT BRANDYWINE ST,0.00,0.00,No,No,No,No,No,No,No,No,No,No,MD,02 - Automobile,2020,HONDA,GRAY,Warning,False,F

In [43]:
print(df.dtypes)
print(f"\nNull values per column:")
print(df.isnull().sum())

date_of_stop                object
time_of_stop                object
description                 object
location                    object
latitude                   float64
longitude                  float64
accident                    object
belts                       object
personal_injury             object
property_damage             object
fatal                       object
commercial_license          object
hazmat                      object
commercial_vehicle          object
alcohol                     object
work_zone                   object
state                       object
vehicle_type                object
year                         int64
make                        object
color                       object
violation_type              object
contributed_to_accident       bool
gender                      object
dtype: object

Null values per column:
date_of_stop               0
time_of_stop               0
description                0
location                   0
latitude                   0
longitude                  0
accident                   0
belts                      0
personal_injury            0
property_damage            0
fatal                      0
commercial_license         0
hazmat                     0
commercial_vehicle         0
alcohol                    0
work_zone                  0
state                      0
vehicle_type               0
year                       0
make                       0
color                      0
violation_type             0
contributed_to_accident    0
gender                     0
dtype: int64

In [44]:
df['date_of_stop'] = pd.to_datetime(df['date_of_stop'], errors='coerce')

print(df['date_of_stop'].dtype)
print(df['date_of_stop'].head())
print(f"\nNull values: {df['date_of_stop'].isnull().sum()}")

datetime64[ns]
0   2023-05-01
1   2023-08-31
2   2023-08-31
3   2023-08-31
4   2023-08-31
Name: date_of_stop, dtype: datetime64[ns]

Null values: 0

In [45]:
df['latitude'] = df['latitude'].replace(0.00, np.nan)
df['longitude'] = df['longitude'].replace(0.00, np.nan)

In [46]:
df.to_csv("../traffic_violations_cleaned.csv", index=False)

In [47]:
print(f"Saved! Shape: {df.shape}")
print(f"Null latitude: {df['latitude'].isnull().sum()}")

Saved! Shape: (1499945, 24)
Null latitude: 114087

In [48]:
df.to_csv("../traffic_violations_cleaned.csv", index=False)
print("Saved successfully!")

Saved successfully!