In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import os
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../Transportation ang Logistics Tracking Datasets/Transportation and Logistics Tracking Dataset.csv", encoding="latin-1", low_memory=False)

In [3]:
df

,Delivery Id,Origin_Location,Destination_Location,region,created_at,actual_delivery_time,On time Delivery,Customer_rating,condition_text,Fixed Costs,Maintenance,Difference,Area,Delivery_Time,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,MVCV0000927/082021,"TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU","ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA",Karnataka,2/6/2015 22:24,2/6/2015 23:27,1.0,4.0,Partly cloudy,10503.0,1012.0,9491.0,Rural,61.0,NaN,NaN,NaN,NaN,NaN
1,VCV00014271/082021,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",Tamil Nadu,2/10/2015 21:49,2/10/2015 22:56,1.0,5.0,Sunny,6092.0,1562.0,4530.0,Rural,62.0,NaN,NaN,NaN,NaN,NaN
2,VCV00014382/082021,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",Pondichery,1/22/2015 20:39,1/22/2015 21:09,1.0,3.0,cloudy,11931.0,1324.0,10607.0,Rural,38.0,NaN,NaN,NaN,NaN,NaN
3,VCV00014743/082021,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",Tamil Nadu,2/3/2015 21:21,2/3/2015 22:13,1.0,3.0,Cloudy,7428.0,560.0,6868.0,Rural,49.0,NaN,NaN,NaN,NaN,NaN
4,VCV00014744/082021,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",Pondichery,2/15/2015 2:40,2/15/2015 3:20,1.0,3.0,Cloudy,6735.0,648.0,6087.0,Rural,39.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
(df.isnull().sum() / len(df) * 100).round(2)

Delivery Id              99.93
Origin_Location          99.93
Destination_Location     99.93
region                   99.93
created_at               99.93
actual_delivery_time     99.93
On time Delivery         99.93
Customer_rating          99.93
condition_text           99.93
Fixed Costs              99.93
Maintenance              99.93
Difference               99.93
Area                     99.99
Delivery_Time            99.99
Unnamed: 14             100.00
Unnamed: 15             100.00
Unnamed: 16             100.00
Unnamed: 17             100.00
Unnamed: 18             100.00
dtype: float64

In [5]:
df.isnull().sum()

Delivery Id             1047859
Origin_Location         1047859
Destination_Location    1047859
region                  1047859
created_at              1047859
actual_delivery_time    1047860
On time Delivery        1047859
Customer_rating         1047859
condition_text          1047859
Fixed Costs             1047858
Maintenance             1047858
Difference              1047858
Area                    1048505
Delivery_Time           1048505
Unnamed: 14             1048563
Unnamed: 15             1048563
Unnamed: 16             1048563
Unnamed: 17             1048563
Unnamed: 18             1048563
dtype: int64

In [6]:
print(f"\nTotal rows: {len(df)}")

Total rows: 1048563

In [7]:
df.shape

(1048563, 19)

In [8]:
df = df.dropna(how='all')

In [9]:
dfexe = [
    'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 
    'Unnamed: 17', 'Unnamed: 18',
    'Area',
    'Difference',
    'Delivery Id' 
]
df = df.drop(columns=dfexe)
print(df.shape)

(705, 11)

In [10]:
df.isnull().sum()

Origin_Location           1
Destination_Location      1
region                    1
created_at                1
actual_delivery_time      2
On time Delivery          1
Customer_rating           1
condition_text            1
Fixed Costs               0
Maintenance               0
Delivery_Time           647
dtype: int64

In [11]:
df = df.dropna(subset=[
    'Origin_Location', 'Destination_Location', 'region',
    'created_at', 'On time Delivery', 'Customer_rating', 'condition_text'
])
print(f"Rows remaining: {len(df)}")

Rows remaining: 704

In [12]:
df = df.copy()
df['Delivery_Time'] = df['Delivery_Time'].fillna(df['Delivery_Time'].median())

In [13]:
df = df.dropna(subset=['actual_delivery_time'])
print(f"Rows remaining: {len(df)}")

Rows remaining: 703

In [14]:
df.isnull().sum()

Origin_Location         0
Destination_Location    0
region                  0
created_at              0
actual_delivery_time    0
On time Delivery        0
Customer_rating         0
condition_text          0
Fixed Costs             0
Maintenance             0
Delivery_Time           0
dtype: int64

In [15]:
df

,Origin_Location,Destination_Location,region,created_at,actual_delivery_time,On time Delivery,Customer_rating,condition_text,Fixed Costs,Maintenance,Delivery_Time
0,"TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU","ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA",Karnataka,2/6/2015 22:24,2/6/2015 23:27,1.0,4.0,Partly cloudy,10503.0,1012.0,61.0
1,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",Tamil Nadu,2/10/2015 21:49,2/10/2015 22:56,1.0,5.0,Sunny,6092.0,1562.0,62.0
2,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",Pondichery,1/22/2015 20:39,1/22/2015 21:09,1.0,3.0,cloudy,11931.0,1324.0,38.0
3,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",Tamil Nadu,2/3/2015 21:21,2/3/2015 22:13,1.0,3.0,Cloudy,7428.0,560.0,49.0
4,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",Pondichery,2/15/2015 2:40,2/15/2015 3:20,1.0,3.0,Cloudy,6735.0,648.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...
700,"Vellaripatti, Madurai, Tamil Nadu","Devalapura, Mysore, Karnataka",Karnataka,2/13/2015 4:00,2/13/2015 4:45,1.0,4.0,Sunny,8164.0,405.0,29.0
701,"Vellaripatti, Madurai, Tamil Nadu","Devalapura, Mysore, Karnataka",Karnataka,2/3/2015 21:26,2/3/2015 22:01,1.0,5.0,Sunny,6380.0,1253.0,29.0
702,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",Tamil Nadu,1/31/2015 2:05,1/31/2015 3:05,1.0,3.0,Sunny,7189.0,511.0,29.0
703,"TVS MOTOR COMPANY-HOSUR,Hosur,TAMIL NADU","TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU",Tamil Nadu,2/1/2015 23:41,2/2/2015 0:14,1.0,4.0,Sunny,10839.0,1326.0,29.0
704,"Vellaripatti, Madurai, Tamil Nadu","Devalapura, Mysore, Karnataka",Karnataka,1/27/2015 21:37,1/27/2015 21:59,1.0,5.0,Sunny,10963.0,1607.0,29.0

In [16]:
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
df['actual_delivery_time'] = pd.to_datetime(df['actual_delivery_time'], errors='coerce')

print(df['created_at'].dtype)
print(df['actual_delivery_time'].dtype)

datetime64[ns]
datetime64[ns]

In [17]:
df['hour'] = df['actual_delivery_time'].dt.hour
df['day_of_week'] = df['actual_delivery_time'].dt.dayofweek
df['month'] = df['actual_delivery_time'].dt.month
df['delivery_duration'] = (df['actual_delivery_time'] - df['created_at']).dt.total_seconds() / 3600

In [18]:
df = df.drop(columns=['created_at', 'actual_delivery_time'])

In [19]:
df['On time Delivery'] = df['On time Delivery'].astype(int)
df['Customer_rating'] = df['Customer_rating'].astype(int)
df['Fixed Costs'] = df['Fixed Costs'].astype(int)
df['Maintenance'] = df['Maintenance'].astype(int)
df['Delivery_Time'] = df['Delivery_Time'].astype(int)
df['delivery_duration'] = df['delivery_duration'].astype(int)

In [20]:
df.dtypes

Origin_Location         object
Destination_Location    object
region                  object
On time Delivery         int64
Customer_rating          int64
condition_text          object
Fixed Costs              int64
Maintenance              int64
Delivery_Time            int64
hour                     int32
day_of_week              int32
month                    int32
delivery_duration        int64
dtype: object

In [21]:
print(df['condition_text'].value_counts())
print(df['region'].value_counts())
print(df['Origin_Location'].value_counts())
print(df['Destination_Location'].value_counts())

condition_text
Sunny                             335
Partly cloudy                     130
Patchy rain possible              111
Mist                               88
Cloudy                             26
Light rain shower                   4
Overcast                            3
Moderate or heavy rain shower       3
cloudy                              1
Patchy light rain with thunder      1
Clear                               1
Name: count, dtype: int64
region
Tamil Nadu     480
Karnataka      125
Pondichery      71
Maharashtra     26
m                1
Name: count, dtype: int64
Origin_Location
DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,TAMIL NADU    278
ASHOK LEYLAND PLANT 2-HOSUR,HOSUR,KARNATAKA                  94
LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY                        67
Bandra,Mumbai                                                58
LUCAS TVS LTD-AMBATTUR,CHENNAI,TAMIL NADU                    35
ASHOK LEYLAND ENNORE,CHENNAI,TAMIL NADU                      30
Vellaripatti, Madurai, Tamil Nadu                            24
TRACTORS & FARM EQUIPMENT LIMITED,KANCHIPURAM,TAMIL NADU     20
Jagadambigainagar, Tiruvallur, Tamil Nadu                    15
Naickenpalayam, Coimbatore, Tamil Nadu                       13
Pozhal, Tiruvallur, Tamil Nadu                               10
Pondur, Kanchipuram, Tamil Nadu                               8
TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU                          8
WABCO INDIA LTD-AMBATTUR,CHENNAI,TAMIL NADU                   7
PRAVEEN ENGINEERING INDUSTRIES,HOSUR,TAMIL NADU               7
ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA                  6
Gopanapalli, Krishnagiri, Tamil Nadu                          5
Perukkaranai, Kanchipuram, Tamil Nadu                         4
TVSLSL HUB MATHIGIRI,HOSUR,TAMIL NADU                         3
TVS MOTOR COMPANY-HOSUR,Hosur,TAMIL NADU                      3
Mookandapalli, Krishnagiri, Tamil Nadu                        3
TURBO ENERGY LTD-PULIVALAM,VELLORE,TAMIL NADU                 2
JAY BHARAT MARUTI LTD,AHMEDABAD,GUJARAT                       1
ASHOK LEYLAND PARTS-HOSUR,HOSUR,TAMIL NADU                    1
Ramamurthy Nagar, Bangalore, Karnataka                        1
Name: count, dtype: int64
Destination_Location
DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,TAMIL NADU      278
ASHOK LEYLAND PLANT 2-HOSUR,HOSUR,KARNATAKA                    93
LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY                          72
LUCAS TVS LTD-AMBATTUR,CHENNAI,TAMIL NADU                      30
Bandra,Mumbai                                                  27
Pondur, Kanchipuram, Tamil Nadu                                26
Devalapura, Mysore, Karnataka                                  25
Onnalvadi, Krishnagiri, Tamil Nadu                             20
TRACTORS & FARMS EQUIPMENTS LIMITED,KANCHIPURAM,TAMIL NADU     20
TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU                           19
ASHOK LEYLAND ENNORE,CHENNAI,TAMIL NADU                        17
Guruvoyal, Tiruvallur, Tamil Nadu                              13
Mookandapalli, Krishnagiri, Tamil Nadu                         12
ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA                   11
Jagadambigainagar, Tiruvallur, Tamil Nadu                       8
WABCO INDIA LTD,HOSUR,TAMIL NADU                                7
SRI DEVI POWDER COATING INDUSTRIES,CHENNAI,TAMIL NADU           7
Kamarajnagar, Tiruvallur, Tamil Nadu                            6
Athipattu, Tiruvallur, Tamil Nadu                               3
TVSLSL HUB MATHIGIRI,HOSUR,TAMIL NADU                           2
ASHOK LEYLAND PARTS-HOSUR,HOSUR,TAMIL NADU                      2
TURBO ENERGY LTD-PULIVALAM,VELLORE,TAMIL NADU                   2
WABCO INDIA LTD-AMBATTUR,CHENNAI,TAMIL NADU                     1
JAY BHARAT MARUTI LIMITED. (J-III-N),GURGAON,Haryana            1
Sahakaranagar P.O, Bangalore, Karnataka                         1
Name: count, dtype: int64

In [22]:
def categorize_weather(condition):
    condition = str(condition).upper()
    if 'SUNNY' in condition or 'CLEAR' in condition:
        return 'CLEAR'
    elif 'CLOUDY' in condition or 'OVERCAST' in condition:
        return 'CLOUDY'
    elif 'RAIN' in condition or 'MIST' in condition or 'THUNDER' in condition:
        return 'RAINY'
    else:
        return 'OTHER'

df['condition_text'] = df['condition_text'].apply(categorize_weather)
print(df['condition_text'].value_counts())

condition_text
CLEAR     336
RAINY     207
CLOUDY    160
Name: count, dtype: int64

In [23]:
df['region'] = df['region'].str.strip().str.title()
df['region'] = df['region'].replace({'M': 'Maharashtra'})
print(df['region'].value_counts())

region
Tamil Nadu     480
Karnataka      125
Pondichery      71
Maharashtra     27
Name: count, dtype: int64

In [24]:
def extract_state(location):
    location = str(location).upper()
    if 'TAMIL NADU' in location:
        return 'Tamil Nadu'
    elif 'KARNATAKA' in location:
        return 'Karnataka'
    elif 'PONDICHERRY' in location or 'PONDY' in location:
        return 'Pondicherry'
    elif 'MAHARASHTRA' in location or 'MUMBAI' in location:
        return 'Maharashtra'
    elif 'GUJARAT' in location:
        return 'Gujarat'
    elif 'HARYANA' in location:
        return 'Haryana'
    else:
        return 'OTHER'

df['Origin_Location'] = df['Origin_Location'].apply(extract_state)
df['Destination_Location'] = df['Destination_Location'].apply(extract_state)

print(df['Origin_Location'].value_counts())
print(df['Destination_Location'].value_counts())

Origin_Location
Tamil Nadu     476
Karnataka      101
Pondicherry     67
Maharashtra     58
Gujarat          1
Name: count, dtype: int64
Destination_Location
Tamil Nadu     473
Karnataka      130
Pondicherry     72
Maharashtra     27
Haryana          1
Name: count, dtype: int64

In [25]:
df = df.rename(columns={
    'Origin_Location': 'Origin',
    'Destination_Location': 'Destination',
    'region': 'Region',
    'On time Delivery': 'On_Time',
    'Customer_rating': 'Customer_Rating',
    'condition_text': 'Weather',
    'Delivery_Time': 'Delivery_Time',
    'hour': 'Hour',
    'day_of_week': 'Day_of_Week',
    'month': 'Month',
    'delivery_duration': 'Delivery_Duration'
})

In [26]:
print(df.shape)
print(df.dtypes)
df.head()

(703, 13)
Origin               object
Destination          object
Region               object
On_Time               int64
Customer_Rating       int64
Weather              object
Fixed Costs           int64
Maintenance           int64
Delivery_Time         int64
Hour                  int32
Day_of_Week           int32
Month                 int32
Delivery_Duration     int64
dtype: object

,Origin,Destination,Region,On_Time,Customer_Rating,Weather,Fixed Costs,Maintenance,Delivery_Time,Hour,Day_of_Week,Month,Delivery_Duration
0,Tamil Nadu,Karnataka,Karnataka,1,4,CLOUDY,10503,1012,61,23,4,2,1
1,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,5,CLEAR,6092,1562,62,22,1,2,1
2,Pondicherry,Pondicherry,Pondichery,1,3,CLOUDY,11931,1324,38,21,3,1,0
3,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,3,CLOUDY,7428,560,49,22,1,2,0
4,Pondicherry,Pondicherry,Pondichery,1,3,CLOUDY,6735,648,39,3,6,2,0

In [27]:
df['Delivery_Duration'].value_counts()

Delivery_Duration
0    579
1    120
2      4
Name: count, dtype: int64

In [28]:
df = df.drop(columns=['Delivery_Duration'])

In [29]:
df.shape

(703, 12)

In [30]:
df

,Origin,Destination,Region,On_Time,Customer_Rating,Weather,Fixed Costs,Maintenance,Delivery_Time,Hour,Day_of_Week,Month
0,Tamil Nadu,Karnataka,Karnataka,1,4,CLOUDY,10503,1012,61,23,4,2
1,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,5,CLEAR,6092,1562,62,22,1,2
2,Pondicherry,Pondicherry,Pondichery,1,3,CLOUDY,11931,1324,38,21,3,1
3,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,3,CLOUDY,7428,560,49,22,1,2
4,Pondicherry,Pondicherry,Pondichery,1,3,CLOUDY,6735,648,39,3,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...
700,Tamil Nadu,Karnataka,Karnataka,1,4,CLEAR,8164,405,29,4,4,2
701,Tamil Nadu,Karnataka,Karnataka,1,5,CLEAR,6380,1253,29,22,1,2
702,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,3,CLEAR,7189,511,29,3,5,1
703,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,4,CLEAR,10839,1326,29,0,0,2
704,Tamil Nadu,Karnataka,Karnataka,1,5,CLEAR,10963,1607,29,21,1,1

In [31]:
df['Month'].value_counts()

Month
2    443
1    260
Name: count, dtype: int64

In [32]:
df = df.drop(columns=['Month'])

In [33]:
df

,Origin,Destination,Region,On_Time,Customer_Rating,Weather,Fixed Costs,Maintenance,Delivery_Time,Hour,Day_of_Week
0,Tamil Nadu,Karnataka,Karnataka,1,4,CLOUDY,10503,1012,61,23,4
1,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,5,CLEAR,6092,1562,62,22,1
2,Pondicherry,Pondicherry,Pondichery,1,3,CLOUDY,11931,1324,38,21,3
3,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,3,CLOUDY,7428,560,49,22,1
4,Pondicherry,Pondicherry,Pondichery,1,3,CLOUDY,6735,648,39,3,6
...,...,...,...,...,...,...,...,...,...,...,...
700,Tamil Nadu,Karnataka,Karnataka,1,4,CLEAR,8164,405,29,4,4
701,Tamil Nadu,Karnataka,Karnataka,1,5,CLEAR,6380,1253,29,22,1
702,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,3,CLEAR,7189,511,29,3,5
703,Tamil Nadu,Tamil Nadu,Tamil Nadu,1,4,CLEAR,10839,1326,29,0,0
704,Tamil Nadu,Karnataka,Karnataka,1,5,CLEAR,10963,1607,29,21,1

In [34]:
df['On_Time'].value_counts()

On_Time
1    514
0    189
Name: count, dtype: int64

In [35]:
for col in ['Origin', 'Destination', 'Region', 'Weather']:
    df[col] = df[col].astype('category')

df['On_Time'] = df['On_Time'].astype(bool)

for col in ['Customer_Rating', 'Fixed Costs', 'Maintenance',
            'Delivery_Time', 'Hour', 'Day_of_Week']:
    df[col] = df[col].astype('Int64')

print(df.dtypes)
print(f"\nShape: {df.shape}")

Origin             category
Destination        category
Region             category
On_Time                bool
Customer_Rating       Int64
Weather            category
Fixed Costs           Int64
Maintenance           Int64
Delivery_Time         Int64
Hour                  Int64
Day_of_Week           Int64
dtype: object

Shape: (703, 11)

In [36]:
df.isnull().sum()

Origin             0
Destination        0
Region             0
On_Time            0
Customer_Rating    0
Weather            0
Fixed Costs        0
Maintenance        0
Delivery_Time      0
Hour               0
Day_of_Week        0
dtype: int64

In [37]:
df.dtypes

Origin             category
Destination        category
Region             category
On_Time                bool
Customer_Rating       Int64
Weather            category
Fixed Costs           Int64
Maintenance           Int64
Delivery_Time         Int64
Hour                  Int64
Day_of_Week           Int64
dtype: object

In [39]:
df.to_csv("../Transportation ang Logistics Tracking Datasets/transportation_logistics_cleaned.csv", index=False)
print("Saved successfully!")

Saved successfully!